// Generated by tools/gamecore/generate-core-forwarders.sh from
// cores/GameCore.h. Do not edit by hand.

#include "EmpoAppCore.h"

#include <dlfcn.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "GameCore.h"

static EmpoCoreRunner gRunner = EmpoCoreRunnerApp;
static void *gCore;
static char gCorePath[1024];
// Goes up each time a different core opens. A forwarder looks its
// symbol up again when this changed.
static unsigned gCoreGeneration;
static int gSessionKilled;

void EmpoCoreUseRunner(EmpoCoreRunner runner) {
    gRunner = runner;
}

int EmpoCoreOpen(const char *binaryPath) {
    if (gCore != NULL && strcmp(gCorePath, binaryPath) == 0) {
        gSessionKilled = 0;
        return 1;
    }
    if (gCore != NULL && !gSessionKilled) {
        // The open core still holds a game, and its threads, globals
        // and working directory would run next to the new engine.
        fprintf(stderr, "EmpoCore: %s holds a game, refusing %s\n", gCorePath, binaryPath);
        return 0;
    }
    // RTLD_LOCAL keeps the core's names out of the global namespace.
    // Every name below reaches this image through its own handle.
    //
    // A killed core stays loaded: dlclose does not unload an image that
    // ran static initializers or registered ObjC classes. It holds no
    // game, and scripts/audit-ipa.sh keeps its class names its own.
    void *core = dlopen(binaryPath, RTLD_NOW | RTLD_LOCAL);
    if (core == NULL) {
        fprintf(stderr, "EmpoCore: cannot open %s: %s\n", binaryPath, dlerror());
        return 0;
    }
    gCore = core;
    gCoreGeneration++;
    gSessionKilled = 0;
    snprintf(gCorePath, sizeof(gCorePath), "%s", binaryPath);
    return 1;
}

void EmpoCoreKillSession(void) {
    gamecore_killSession();
    gSessionKilled = 1;
}

int EmpoCoreIsOpen(void) {
    return gRunner == EmpoCoreRunnerGameProcess ? EmpoGameProcessIsOpen() : gCore != NULL;
}

// dlsym with the core's handle searches that image only, so each core
// answers under the same name without a clash with the forwarder below
// or with another core that stays loaded after a kill.
static void *coreSymbol(const char *symbol) {
    void *address = gCore != NULL ? dlsym(gCore, symbol) : NULL;
    if (address == NULL) {
        // Either the app called the core before it picked a game, or
        // the framework and this file were built from different
        // headers. Both are build errors, and a silent no-op would hide
        // them until a game misbehaved.
        fprintf(stderr, "EmpoCore: %s is not available (core open: %d)\n", symbol, gCore != NULL);
        abort();
    }
    return address;
}

int gameprocess_run_app(int argc, char **argv);

int gamecore_run_app(int argc, char **argv) {
    if (gRunner == EmpoCoreRunnerGameProcess) {
        return gameprocess_run_app(argc, argv);
    }
    static int (*fn)(int argc, char **argv);
    static unsigned generation;
    if (fn == NULL || generation != gCoreGeneration) {
        fn = coreSymbol("gamecore_run_app");
        generation = gCoreGeneration;
    }
    return fn(argc, argv);
}

int gameprocess_isGameReady(void);

int gamecore_isGameReady(void) {
    if (gRunner == EmpoCoreRunnerGameProcess) {
        return gameprocess_isGameReady();
    }
    static int (*fn)(void);
    static unsigned generation;
    if (fn == NULL || generation != gCoreGeneration) {
        fn = coreSymbol("gamecore_isGameReady");
        generation = gCoreGeneration;
    }
    return fn();
}

void gameprocess_setGamePath(const char *path);

void gamecore_setGamePath(const char *path) {
    if (gRunner == EmpoCoreRunnerGameProcess) {
        gameprocess_setGamePath(path);
        return;
    }
    static void (*fn)(const char *path);
    static unsigned generation;
    if (fn == NULL || generation != gCoreGeneration) {
        fn = coreSymbol("gamecore_setGamePath");
        generation = gCoreGeneration;
    }
    fn(path);
}

int gameprocess_isEngineTerminated(void);

int gamecore_isEngineTerminated(void) {
    if (gRunner == EmpoCoreRunnerGameProcess) {
        return gameprocess_isEngineTerminated();
    }
    static int (*fn)(void);
    static unsigned generation;
    if (fn == NULL || generation != gCoreGeneration) {
        fn = coreSymbol("gamecore_isEngineTerminated");
        generation = gCoreGeneration;
    }
    return fn();
}

int gameprocess_didEngineExitCleanly(void);

int gamecore_didEngineExitCleanly(void) {
    if (gRunner == EmpoCoreRunnerGameProcess) {
        return gameprocess_didEngineExitCleanly();
    }
    static int (*fn)(void);
    static unsigned generation;
    if (fn == NULL || generation != gCoreGeneration) {
        fn = coreSymbol("gamecore_didEngineExitCleanly");
        generation = gCoreGeneration;
    }
    return fn();
}

int gameprocess_isEngineHung(void);

int gamecore_isEngineHung(void) {
    if (gRunner == EmpoCoreRunnerGameProcess) {
        return gameprocess_isEngineHung();
    }
    static int (*fn)(void);
    static unsigned generation;
    if (fn == NULL || generation != gCoreGeneration) {
        fn = coreSymbol("gamecore_isEngineHung");
        generation = gCoreGeneration;
    }
    return fn();
}

void gameprocess_setEngineTerminatedCallback(gamecore_EngineTerminatedCallback cb, void *userdata);

void gamecore_setEngineTerminatedCallback(gamecore_EngineTerminatedCallback cb, void *userdata) {
    if (gRunner == EmpoCoreRunnerGameProcess) {
        gameprocess_setEngineTerminatedCallback(cb, userdata);
        return;
    }
    static void (*fn)(gamecore_EngineTerminatedCallback cb, void *userdata);
    static unsigned generation;
    if (fn == NULL || generation != gCoreGeneration) {
        fn = coreSymbol("gamecore_setEngineTerminatedCallback");
        generation = gCoreGeneration;
    }
    fn(cb, userdata);
}

void gameprocess_setGameRectChangedCallback(gamecore_GameRectChangedCallback cb, void *userdata);

void gamecore_setGameRectChangedCallback(gamecore_GameRectChangedCallback cb, void *userdata) {
    if (gRunner == EmpoCoreRunnerGameProcess) {
        gameprocess_setGameRectChangedCallback(cb, userdata);
        return;
    }
    static void (*fn)(gamecore_GameRectChangedCallback cb, void *userdata);
    static unsigned generation;
    if (fn == NULL || generation != gCoreGeneration) {
        fn = coreSymbol("gamecore_setGameRectChangedCallback");
        generation = gCoreGeneration;
    }
    fn(cb, userdata);
}

void gameprocess_injectKeyEvent(int scancode, int pressed);

void gamecore_injectKeyEvent(int scancode, int pressed) {
    if (gRunner == EmpoCoreRunnerGameProcess) {
        gameprocess_injectKeyEvent(scancode, pressed);
        return;
    }
    static void (*fn)(int scancode, int pressed);
    static unsigned generation;
    if (fn == NULL || generation != gCoreGeneration) {
        fn = coreSymbol("gamecore_injectKeyEvent");
        generation = gCoreGeneration;
    }
    fn(scancode, pressed);
}

void gameprocess_setLauncherIdentity(const char *name);

void gamecore_setLauncherIdentity(const char *name) {
    if (gRunner == EmpoCoreRunnerGameProcess) {
        gameprocess_setLauncherIdentity(name);
        return;
    }
    static void (*fn)(const char *name);
    static unsigned generation;
    if (fn == NULL || generation != gCoreGeneration) {
        fn = coreSymbol("gamecore_setLauncherIdentity");
        generation = gCoreGeneration;
    }
    fn(name);
}

void gameprocess_setCABundlePath(const char *path);

void gamecore_setCABundlePath(const char *path) {
    if (gRunner == EmpoCoreRunnerGameProcess) {
        gameprocess_setCABundlePath(path);
        return;
    }
    static void (*fn)(const char *path);
    static unsigned generation;
    if (fn == NULL || generation != gCoreGeneration) {
        fn = coreSymbol("gamecore_setCABundlePath");
        generation = gCoreGeneration;
    }
    fn(path);
}

void gameprocess_setTextInputModeCallback(gamecore_TextInputModeCallback cb, void *userdata);

void gamecore_setTextInputModeCallback(gamecore_TextInputModeCallback cb, void *userdata) {
    if (gRunner == EmpoCoreRunnerGameProcess) {
        gameprocess_setTextInputModeCallback(cb, userdata);
        return;
    }
    static void (*fn)(gamecore_TextInputModeCallback cb, void *userdata);
    static unsigned generation;
    if (fn == NULL || generation != gCoreGeneration) {
        fn = coreSymbol("gamecore_setTextInputModeCallback");
        generation = gCoreGeneration;
    }
    fn(cb, userdata);
}

void gameprocess_pushTextInput(const char *utf8);

void gamecore_pushTextInput(const char *utf8) {
    if (gRunner == EmpoCoreRunnerGameProcess) {
        gameprocess_pushTextInput(utf8);
        return;
    }
    static void (*fn)(const char *utf8);
    static unsigned generation;
    if (fn == NULL || generation != gCoreGeneration) {
        fn = coreSymbol("gamecore_pushTextInput");
        generation = gCoreGeneration;
    }
    fn(utf8);
}

int gameprocess_isTextInputActive(void);

int gamecore_isTextInputActive(void) {
    if (gRunner == EmpoCoreRunnerGameProcess) {
        return gameprocess_isTextInputActive();
    }
    static int (*fn)(void);
    static unsigned generation;
    if (fn == NULL || generation != gCoreGeneration) {
        fn = coreSymbol("gamecore_isTextInputActive");
        generation = gCoreGeneration;
    }
    return fn();
}

double gameprocess_getAverageFPS(void);

double gamecore_getAverageFPS(void) {
    if (gRunner == EmpoCoreRunnerGameProcess) {
        return gameprocess_getAverageFPS();
    }
    static double (*fn)(void);
    static unsigned generation;
    if (fn == NULL || generation != gCoreGeneration) {
        fn = coreSymbol("gamecore_getAverageFPS");
        generation = gCoreGeneration;
    }
    return fn();
}

int gameprocess_getTargetFPS(void);

int gamecore_getTargetFPS(void) {
    if (gRunner == EmpoCoreRunnerGameProcess) {
        return gameprocess_getTargetFPS();
    }
    static int (*fn)(void);
    static unsigned generation;
    if (fn == NULL || generation != gCoreGeneration) {
        fn = coreSymbol("gamecore_getTargetFPS");
        generation = gCoreGeneration;
    }
    return fn();
}

const char *gameprocess_getGameTitle(void);

const char *gamecore_getGameTitle(void) {
    if (gRunner == EmpoCoreRunnerGameProcess) {
        return gameprocess_getGameTitle();
    }
    static const char *(*fn)(void);
    static unsigned generation;
    if (fn == NULL || generation != gCoreGeneration) {
        fn = coreSymbol("gamecore_getGameTitle");
        generation = gCoreGeneration;
    }
    return fn();
}

void gameprocess_setSafeAreaInsets(float top, float bottom, float left, float right);

void gamecore_setSafeAreaInsets(float top, float bottom, float left, float right) {
    if (gRunner == EmpoCoreRunnerGameProcess) {
        gameprocess_setSafeAreaInsets(top, bottom, left, right);
        return;
    }
    static void (*fn)(float top, float bottom, float left, float right);
    static unsigned generation;
    if (fn == NULL || generation != gCoreGeneration) {
        fn = coreSymbol("gamecore_setSafeAreaInsets");
        generation = gCoreGeneration;
    }
    fn(top, bottom, left, right);
}

void gameprocess_setHostViewportRegion(float x, float y, float w, float h, bool isPortrait);

void gamecore_setHostViewportRegion(float x, float y, float w, float h, bool isPortrait) {
    if (gRunner == EmpoCoreRunnerGameProcess) {
        gameprocess_setHostViewportRegion(x, y, w, h, isPortrait);
        return;
    }
    static void (*fn)(float x, float y, float w, float h, bool isPortrait);
    static unsigned generation;
    if (fn == NULL || generation != gCoreGeneration) {
        fn = coreSymbol("gamecore_setHostViewportRegion");
        generation = gCoreGeneration;
    }
    fn(x, y, w, h, isPortrait);
}

void gameprocess_clearHostViewportRegion(void);

void gamecore_clearHostViewportRegion(void) {
    if (gRunner == EmpoCoreRunnerGameProcess) {
        gameprocess_clearHostViewportRegion();
        return;
    }
    static void (*fn)(void);
    static unsigned generation;
    if (fn == NULL || generation != gCoreGeneration) {
        fn = coreSymbol("gamecore_clearHostViewportRegion");
        generation = gCoreGeneration;
    }
    fn();
}

void *gameprocess_getGameWindow(void);

void *gamecore_getGameWindow(void) {
    if (gRunner == EmpoCoreRunnerGameProcess) {
        return gameprocess_getGameWindow();
    }
    static void *(*fn)(void);
    static unsigned generation;
    if (fn == NULL || generation != gCoreGeneration) {
        fn = coreSymbol("gamecore_getGameWindow");
        generation = gCoreGeneration;
    }
    return fn();
}

GameCoreVerticalAlignment gameprocess_getVerticalAlignment(void);

GameCoreVerticalAlignment gamecore_getVerticalAlignment(void) {
    if (gRunner == EmpoCoreRunnerGameProcess) {
        return gameprocess_getVerticalAlignment();
    }
    static GameCoreVerticalAlignment (*fn)(void);
    static unsigned generation;
    if (fn == NULL || generation != gCoreGeneration) {
        fn = coreSymbol("gamecore_getVerticalAlignment");
        generation = gCoreGeneration;
    }
    return fn();
}

void gameprocess_applySessionConfig(const GameCoreSessionConfig *config);

void gamecore_applySessionConfig(const GameCoreSessionConfig *config) {
    if (gRunner == EmpoCoreRunnerGameProcess) {
        gameprocess_applySessionConfig(config);
        return;
    }
    static void (*fn)(const GameCoreSessionConfig *config);
    static unsigned generation;
    if (fn == NULL || generation != gCoreGeneration) {
        fn = coreSymbol("gamecore_applySessionConfig");
        generation = gCoreGeneration;
    }
    fn(config);
}

void gameprocess_setSetting(const char *key, const char *value);

void gamecore_setSetting(const char *key, const char *value) {
    if (gRunner == EmpoCoreRunnerGameProcess) {
        gameprocess_setSetting(key, value);
        return;
    }
    static void (*fn)(const char *key, const char *value);
    static unsigned generation;
    if (fn == NULL || generation != gCoreGeneration) {
        fn = coreSymbol("gamecore_setSetting");
        generation = gCoreGeneration;
    }
    fn(key, value);
}

const char *gameprocess_getDetails(void);

const char *gamecore_getDetails(void) {
    if (gRunner == EmpoCoreRunnerGameProcess) {
        return gameprocess_getDetails();
    }
    static const char *(*fn)(void);
    static unsigned generation;
    if (fn == NULL || generation != gCoreGeneration) {
        fn = coreSymbol("gamecore_getDetails");
        generation = gCoreGeneration;
    }
    return fn();
}

void gameprocess_setShowViewportBounds(bool enabled);

void gamecore_setShowViewportBounds(bool enabled) {
    if (gRunner == EmpoCoreRunnerGameProcess) {
        gameprocess_setShowViewportBounds(enabled);
        return;
    }
    static void (*fn)(bool enabled);
    static unsigned generation;
    if (fn == NULL || generation != gCoreGeneration) {
        fn = coreSymbol("gamecore_setShowViewportBounds");
        generation = gCoreGeneration;
    }
    fn(enabled);
}

void gameprocess_setCheatsEnabled(bool enabled);

void gamecore_setCheatsEnabled(bool enabled) {
    if (gRunner == EmpoCoreRunnerGameProcess) {
        gameprocess_setCheatsEnabled(enabled);
        return;
    }
    static void (*fn)(bool enabled);
    static unsigned generation;
    if (fn == NULL || generation != gCoreGeneration) {
        fn = coreSymbol("gamecore_setCheatsEnabled");
        generation = gCoreGeneration;
    }
    fn(enabled);
}

bool gameprocess_getCheatsEnabled(void);

bool gamecore_getCheatsEnabled(void) {
    if (gRunner == EmpoCoreRunnerGameProcess) {
        return gameprocess_getCheatsEnabled();
    }
    static bool (*fn)(void);
    static unsigned generation;
    if (fn == NULL || generation != gCoreGeneration) {
        fn = coreSymbol("gamecore_getCheatsEnabled");
        generation = gCoreGeneration;
    }
    return fn();
}

void gameprocess_setGameControllerCaptureEnabled(bool enabled);

void gamecore_setGameControllerCaptureEnabled(bool enabled) {
    if (gRunner == EmpoCoreRunnerGameProcess) {
        gameprocess_setGameControllerCaptureEnabled(enabled);
        return;
    }
    static void (*fn)(bool enabled);
    static unsigned generation;
    if (fn == NULL || generation != gCoreGeneration) {
        fn = coreSymbol("gamecore_setGameControllerCaptureEnabled");
        generation = gCoreGeneration;
    }
    fn(enabled);
}

void gameprocess_setTouchMouseEnabled(bool enabled);

void gamecore_setTouchMouseEnabled(bool enabled) {
    if (gRunner == EmpoCoreRunnerGameProcess) {
        gameprocess_setTouchMouseEnabled(enabled);
        return;
    }
    static void (*fn)(bool enabled);
    static unsigned generation;
    if (fn == NULL || generation != gCoreGeneration) {
        fn = coreSymbol("gamecore_setTouchMouseEnabled");
        generation = gCoreGeneration;
    }
    fn(enabled);
}

void gameprocess_setViewportBoundsColor(float r, float g, float b, float a);

void gamecore_setViewportBoundsColor(float r, float g, float b, float a) {
    if (gRunner == EmpoCoreRunnerGameProcess) {
        gameprocess_setViewportBoundsColor(r, g, b, a);
        return;
    }
    static void (*fn)(float r, float g, float b, float a);
    static unsigned generation;
    if (fn == NULL || generation != gCoreGeneration) {
        fn = coreSymbol("gamecore_setViewportBoundsColor");
        generation = gCoreGeneration;
    }
    fn(r, g, b, a);
}

void gameprocess_signalErrorDismissed(void);

void gamecore_signalErrorDismissed(void) {
    if (gRunner == EmpoCoreRunnerGameProcess) {
        gameprocess_signalErrorDismissed();
        return;
    }
    static void (*fn)(void);
    static unsigned generation;
    if (fn == NULL || generation != gCoreGeneration) {
        fn = coreSymbol("gamecore_signalErrorDismissed");
        generation = gCoreGeneration;
    }
    fn();
}

void gameprocess_setErrorMessageCallback(gamecore_ErrorMessageCallback cb, void *userdata);

void gamecore_setErrorMessageCallback(gamecore_ErrorMessageCallback cb, void *userdata) {
    if (gRunner == EmpoCoreRunnerGameProcess) {
        gameprocess_setErrorMessageCallback(cb, userdata);
        return;
    }
    static void (*fn)(gamecore_ErrorMessageCallback cb, void *userdata);
    static unsigned generation;
    if (fn == NULL || generation != gCoreGeneration) {
        fn = coreSymbol("gamecore_setErrorMessageCallback");
        generation = gCoreGeneration;
    }
    fn(cb, userdata);
}

void gameprocess_signalInfoDismissed(void);

void gamecore_signalInfoDismissed(void) {
    if (gRunner == EmpoCoreRunnerGameProcess) {
        gameprocess_signalInfoDismissed();
        return;
    }
    static void (*fn)(void);
    static unsigned generation;
    if (fn == NULL || generation != gCoreGeneration) {
        fn = coreSymbol("gamecore_signalInfoDismissed");
        generation = gCoreGeneration;
    }
    fn();
}

void gameprocess_setInfoMessageCallback(gamecore_InfoMessageCallback cb, void *userdata);

void gamecore_setInfoMessageCallback(gamecore_InfoMessageCallback cb, void *userdata) {
    if (gRunner == EmpoCoreRunnerGameProcess) {
        gameprocess_setInfoMessageCallback(cb, userdata);
        return;
    }
    static void (*fn)(gamecore_InfoMessageCallback cb, void *userdata);
    static unsigned generation;
    if (fn == NULL || generation != gCoreGeneration) {
        fn = coreSymbol("gamecore_setInfoMessageCallback");
        generation = gCoreGeneration;
    }
    fn(cb, userdata);
}

void gameprocess_requestPause(void);

void gamecore_requestPause(void) {
    if (gRunner == EmpoCoreRunnerGameProcess) {
        gameprocess_requestPause();
        return;
    }
    static void (*fn)(void);
    static unsigned generation;
    if (fn == NULL || generation != gCoreGeneration) {
        fn = coreSymbol("gamecore_requestPause");
        generation = gCoreGeneration;
    }
    fn();
}

void gameprocess_requestResume(void);

void gamecore_requestResume(void) {
    if (gRunner == EmpoCoreRunnerGameProcess) {
        gameprocess_requestResume();
        return;
    }
    static void (*fn)(void);
    static unsigned generation;
    if (fn == NULL || generation != gCoreGeneration) {
        fn = coreSymbol("gamecore_requestResume");
        generation = gCoreGeneration;
    }
    fn();
}

bool gameprocess_isPaused(void);

bool gamecore_isPaused(void) {
    if (gRunner == EmpoCoreRunnerGameProcess) {
        return gameprocess_isPaused();
    }
    static bool (*fn)(void);
    static unsigned generation;
    if (fn == NULL || generation != gCoreGeneration) {
        fn = coreSymbol("gamecore_isPaused");
        generation = gCoreGeneration;
    }
    return fn();
}

bool gameprocess_copySnapshotRGBA(unsigned char *dest, int destSize, int *width, int *height);

bool gamecore_copySnapshotRGBA(unsigned char *dest, int destSize, int *width, int *height) {
    if (gRunner == EmpoCoreRunnerGameProcess) {
        return gameprocess_copySnapshotRGBA(dest, destSize, width, height);
    }
    static bool (*fn)(unsigned char *dest, int destSize, int *width, int *height);
    static unsigned generation;
    if (fn == NULL || generation != gCoreGeneration) {
        fn = coreSymbol("gamecore_copySnapshotRGBA");
        generation = gCoreGeneration;
    }
    return fn(dest, destSize, width, height);
}

bool gameprocess_getSnapshotSize(int *width, int *height);

bool gamecore_getSnapshotSize(int *width, int *height) {
    if (gRunner == EmpoCoreRunnerGameProcess) {
        return gameprocess_getSnapshotSize(width, height);
    }
    static bool (*fn)(int *width, int *height);
    static unsigned generation;
    if (fn == NULL || generation != gCoreGeneration) {
        fn = coreSymbol("gamecore_getSnapshotSize");
        generation = gCoreGeneration;
    }
    return fn(width, height);
}

void gameprocess_setPausedCallback(gamecore_PausedCallback cb, void *userdata);

void gamecore_setPausedCallback(gamecore_PausedCallback cb, void *userdata) {
    if (gRunner == EmpoCoreRunnerGameProcess) {
        gameprocess_setPausedCallback(cb, userdata);
        return;
    }
    static void (*fn)(gamecore_PausedCallback cb, void *userdata);
    static unsigned generation;
    if (fn == NULL || generation != gCoreGeneration) {
        fn = coreSymbol("gamecore_setPausedCallback");
        generation = gCoreGeneration;
    }
    fn(cb, userdata);
}

void gameprocess_setResumedCallback(gamecore_ResumedCallback cb, void *userdata);

void gamecore_setResumedCallback(gamecore_ResumedCallback cb, void *userdata) {
    if (gRunner == EmpoCoreRunnerGameProcess) {
        gameprocess_setResumedCallback(cb, userdata);
        return;
    }
    static void (*fn)(gamecore_ResumedCallback cb, void *userdata);
    static unsigned generation;
    if (fn == NULL || generation != gCoreGeneration) {
        fn = coreSymbol("gamecore_setResumedCallback");
        generation = gCoreGeneration;
    }
    fn(cb, userdata);
}

void gameprocess_setFrameRenderedCallback(gamecore_FrameRenderedCallback cb, void *userdata);

void gamecore_setFrameRenderedCallback(gamecore_FrameRenderedCallback cb, void *userdata) {
    if (gRunner == EmpoCoreRunnerGameProcess) {
        gameprocess_setFrameRenderedCallback(cb, userdata);
        return;
    }
    static void (*fn)(gamecore_FrameRenderedCallback cb, void *userdata);
    static unsigned generation;
    if (fn == NULL || generation != gCoreGeneration) {
        fn = coreSymbol("gamecore_setFrameRenderedCallback");
        generation = gCoreGeneration;
    }
    fn(cb, userdata);
}

void gameprocess_setFastForwardMultiplier(int multiplier);

void gamecore_setFastForwardMultiplier(int multiplier) {
    if (gRunner == EmpoCoreRunnerGameProcess) {
        gameprocess_setFastForwardMultiplier(multiplier);
        return;
    }
    static void (*fn)(int multiplier);
    static unsigned generation;
    if (fn == NULL || generation != gCoreGeneration) {
        fn = coreSymbol("gamecore_setFastForwardMultiplier");
        generation = gCoreGeneration;
    }
    fn(multiplier);
}

int gameprocess_getFastForwardMultiplier(void);

int gamecore_getFastForwardMultiplier(void) {
    if (gRunner == EmpoCoreRunnerGameProcess) {
        return gameprocess_getFastForwardMultiplier();
    }
    static int (*fn)(void);
    static unsigned generation;
    if (fn == NULL || generation != gCoreGeneration) {
        fn = coreSymbol("gamecore_getFastForwardMultiplier");
        generation = gCoreGeneration;
    }
    return fn();
}

void gameprocess_resetSessionState(void);

void gamecore_resetSessionState(void) {
    if (gRunner == EmpoCoreRunnerGameProcess) {
        gameprocess_resetSessionState();
        return;
    }
    static void (*fn)(void);
    static unsigned generation;
    if (fn == NULL || generation != gCoreGeneration) {
        fn = coreSymbol("gamecore_resetSessionState");
        generation = gCoreGeneration;
    }
    fn();
}

void gameprocess_killSession(void);

void gamecore_killSession(void) {
    if (gRunner == EmpoCoreRunnerGameProcess) {
        gameprocess_killSession();
        return;
    }
    static void (*fn)(void);
    static unsigned generation;
    if (fn == NULL || generation != gCoreGeneration) {
        fn = coreSymbol("gamecore_killSession");
        generation = gCoreGeneration;
    }
    fn();
}

void gameprocess_setDebugLogPath(const char *path);

void gamecore_setDebugLogPath(const char *path) {
    if (gRunner == EmpoCoreRunnerGameProcess) {
        gameprocess_setDebugLogPath(path);
        return;
    }
    static void (*fn)(const char *path);
    static unsigned generation;
    if (fn == NULL || generation != gCoreGeneration) {
        fn = coreSymbol("gamecore_setDebugLogPath");
        generation = gCoreGeneration;
    }
    fn(path);
}
