// Generated by tools/gamecore/generate-core-forwarders.sh from
// ios/Empo/src/App/GameCore.h. Do not edit by hand.

#include "EmpoCore.h"

#include <dlfcn.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "GameCore.h"

static void *gCore;
static char gSymbolPrefix[16];

int EmpoCoreOpen(const char *binaryPath, const char *symbolPrefix) {
    if (gCore != NULL) {
        return 1;
    }
    // RTLD_LOCAL keeps the core's names out of the global namespace, so
    // a second core opened later cannot bind to them. Every name below
    // reaches this image through its own handle.
    gCore = dlopen(binaryPath, RTLD_NOW | RTLD_LOCAL);
    if (gCore == NULL) {
        fprintf(stderr, "EmpoCore: cannot open %s: %s\n", binaryPath, dlerror());
        return 0;
    }
    snprintf(gSymbolPrefix, sizeof(gSymbolPrefix), "%s", symbolPrefix);
    return 1;
}

int EmpoCoreIsOpen(void) {
    return gCore != NULL;
}

// Each core answers this interface under its own prefix: MkxpCore
// answers mkxp_setGamePath, PsdkCore answers psdk_setGamePath. The
// caller of EmpoCoreOpen says which one it opened.
static void *coreSymbol(const char *name) {
    char symbol[96];
    snprintf(symbol, sizeof(symbol), "%s%s", gSymbolPrefix, name);
    void *address = gCore != NULL ? dlsym(gCore, symbol) : NULL;
    if (address == NULL) {
        // Either the app called the core before it picked a game, or
        // the framework and this file were built from different
        // headers. Both are build errors, and a silent no-op would hide
        // them until a game misbehaved.
        fprintf(stderr, "EmpoCore: %s is not available (core open: %d)\n", symbol, gCore != NULL);
        abort();
    }
    return address;
}

int gamecore_run_app(int argc, char **argv) {
    static int (*fn)(int argc, char **argv);
    if (fn == NULL) {
        fn = coreSymbol("run_app");
    }
    return fn(argc, argv);
}

void gamecore_setGameReady(void) {
    static void (*fn)(void);
    if (fn == NULL) {
        fn = coreSymbol("setGameReady");
    }
    fn();
}

int gamecore_isGameReady(void) {
    static int (*fn)(void);
    if (fn == NULL) {
        fn = coreSymbol("isGameReady");
    }
    return fn();
}

void gamecore_setGamePath(const char *path) {
    static void (*fn)(const char *path);
    if (fn == NULL) {
        fn = coreSymbol("setGamePath");
    }
    fn(path);
}

const char *gamecore_waitForGamePath(void) {
    static const char *(*fn)(void);
    if (fn == NULL) {
        fn = coreSymbol("waitForGamePath");
    }
    return fn();
}

void gamecore_requestTerminate(void) {
    static void (*fn)(void);
    if (fn == NULL) {
        fn = coreSymbol("requestTerminate");
    }
    fn();
}

int gamecore_isEngineTerminated(void) {
    static int (*fn)(void);
    if (fn == NULL) {
        fn = coreSymbol("isEngineTerminated");
    }
    return fn();
}

void gamecore_setEngineTerminated(void) {
    static void (*fn)(void);
    if (fn == NULL) {
        fn = coreSymbol("setEngineTerminated");
    }
    fn();
}

int gamecore_didEngineExitCleanly(void) {
    static int (*fn)(void);
    if (fn == NULL) {
        fn = coreSymbol("didEngineExitCleanly");
    }
    return fn();
}

void gamecore_setEngineExitedCleanly(void) {
    static void (*fn)(void);
    if (fn == NULL) {
        fn = coreSymbol("setEngineExitedCleanly");
    }
    fn();
}

int gamecore_isEngineHung(void) {
    static int (*fn)(void);
    if (fn == NULL) {
        fn = coreSymbol("isEngineHung");
    }
    return fn();
}

void gamecore_setEngineHung(void) {
    static void (*fn)(void);
    if (fn == NULL) {
        fn = coreSymbol("setEngineHung");
    }
    fn();
}

void gamecore_setEngineTerminatedCallback(gamecore_EngineTerminatedCallback cb, void *userdata) {
    static void (*fn)(gamecore_EngineTerminatedCallback cb, void *userdata);
    if (fn == NULL) {
        fn = coreSymbol("setEngineTerminatedCallback");
    }
    fn(cb, userdata);
}

void gamecore_setGameRectChangedCallback(gamecore_GameRectChangedCallback cb, void *userdata) {
    static void (*fn)(gamecore_GameRectChangedCallback cb, void *userdata);
    if (fn == NULL) {
        fn = coreSymbol("setGameRectChangedCallback");
    }
    fn(cb, userdata);
}

void gamecore_injectKeyEvent(int scancode, int pressed) {
    static void (*fn)(int scancode, int pressed);
    if (fn == NULL) {
        fn = coreSymbol("injectKeyEvent");
    }
    fn(scancode, pressed);
}

void gamecore_setKeyEventCallback(gamecore_KeyEventCallback cb, void *userdata) {
    static void (*fn)(gamecore_KeyEventCallback cb, void *userdata);
    if (fn == NULL) {
        fn = coreSymbol("setKeyEventCallback");
    }
    fn(cb, userdata);
}

void gamecore_injectPointerEvent(int x, int y, GameCorePointerPhase phase) {
    static void (*fn)(int x, int y, GameCorePointerPhase phase);
    if (fn == NULL) {
        fn = coreSymbol("injectPointerEvent");
    }
    fn(x, y, phase);
}

void gamecore_setManagedConfigDir(const char *path) {
    static void (*fn)(const char *path);
    if (fn == NULL) {
        fn = coreSymbol("setManagedConfigDir");
    }
    fn(path);
}

const char *gamecore_getManagedConfigDir(void) {
    static const char *(*fn)(void);
    if (fn == NULL) {
        fn = coreSymbol("getManagedConfigDir");
    }
    return fn();
}

void gamecore_setConfigOverlayJSON(const char *jsonUTF8) {
    static void (*fn)(const char *jsonUTF8);
    if (fn == NULL) {
        fn = coreSymbol("setConfigOverlayJSON");
    }
    fn(jsonUTF8);
}

const char *gamecore_getConfigOverlayJSON(void) {
    static const char *(*fn)(void);
    if (fn == NULL) {
        fn = coreSymbol("getConfigOverlayJSON");
    }
    return fn();
}

void gamecore_setUserDataDirectory(const char *path) {
    static void (*fn)(const char *path);
    if (fn == NULL) {
        fn = coreSymbol("setUserDataDirectory");
    }
    fn(path);
}

const char *gamecore_getUserDataDirectory(void) {
    static const char *(*fn)(void);
    if (fn == NULL) {
        fn = coreSymbol("getUserDataDirectory");
    }
    return fn();
}

void gamecore_setSharedFontsDirectory(const char *path) {
    static void (*fn)(const char *path);
    if (fn == NULL) {
        fn = coreSymbol("setSharedFontsDirectory");
    }
    fn(path);
}

const char *gamecore_getSharedFontsDirectory(void) {
    static const char *(*fn)(void);
    if (fn == NULL) {
        fn = coreSymbol("getSharedFontsDirectory");
    }
    return fn();
}

void gamecore_setLauncherIdentity(const char *name) {
    static void (*fn)(const char *name);
    if (fn == NULL) {
        fn = coreSymbol("setLauncherIdentity");
    }
    fn(name);
}

const char *gamecore_getLauncherIdentity(void) {
    static const char *(*fn)(void);
    if (fn == NULL) {
        fn = coreSymbol("getLauncherIdentity");
    }
    return fn();
}

void gamecore_setCABundlePath(const char *path) {
    static void (*fn)(const char *path);
    if (fn == NULL) {
        fn = coreSymbol("setCABundlePath");
    }
    fn(path);
}

const char *gamecore_getCABundlePath(void) {
    static const char *(*fn)(void);
    if (fn == NULL) {
        fn = coreSymbol("getCABundlePath");
    }
    return fn();
}

void gamecore_setTextInputModeCallback(gamecore_TextInputModeCallback cb, void *userdata) {
    static void (*fn)(gamecore_TextInputModeCallback cb, void *userdata);
    if (fn == NULL) {
        fn = coreSymbol("setTextInputModeCallback");
    }
    fn(cb, userdata);
}

void gamecore_pushTextInput(const char *utf8) {
    static void (*fn)(const char *utf8);
    if (fn == NULL) {
        fn = coreSymbol("pushTextInput");
    }
    fn(utf8);
}

int gamecore_isTextInputActive(void) {
    static int (*fn)(void);
    if (fn == NULL) {
        fn = coreSymbol("isTextInputActive");
    }
    return fn();
}

double gamecore_getAverageFPS(void) {
    static double (*fn)(void);
    if (fn == NULL) {
        fn = coreSymbol("getAverageFPS");
    }
    return fn();
}

int gamecore_getTargetFPS(void) {
    static int (*fn)(void);
    if (fn == NULL) {
        fn = coreSymbol("getTargetFPS");
    }
    return fn();
}

int gamecore_getRGSSVersion(void) {
    static int (*fn)(void);
    if (fn == NULL) {
        fn = coreSymbol("getRGSSVersion");
    }
    return fn();
}

const char *gamecore_getGameTitle(void) {
    static const char *(*fn)(void);
    if (fn == NULL) {
        fn = coreSymbol("getGameTitle");
    }
    return fn();
}

int gamecore_getSupportedRGSSVersionMask(void) {
    static int (*fn)(void);
    if (fn == NULL) {
        fn = coreSymbol("getSupportedRGSSVersionMask");
    }
    return fn();
}

const char *gamecore_getRubyVersion(void) {
    static const char *(*fn)(void);
    if (fn == NULL) {
        fn = coreSymbol("getRubyVersion");
    }
    return fn();
}

const char *gamecore_getANGLEVersion(void) {
    static const char *(*fn)(void);
    if (fn == NULL) {
        fn = coreSymbol("getANGLEVersion");
    }
    return fn();
}

const char *gamecore_getMetalDeviceName(void) {
    static const char *(*fn)(void);
    if (fn == NULL) {
        fn = coreSymbol("getMetalDeviceName");
    }
    return fn();
}

void gamecore_setGameRect(float x, float y, float w, float h) {
    static void (*fn)(float x, float y, float w, float h);
    if (fn == NULL) {
        fn = coreSymbol("setGameRect");
    }
    fn(x, y, w, h);
}

void gamecore_getSafeAreaInsets(float *top, float *bottom, float *left, float *right) {
    static void (*fn)(float *top, float *bottom, float *left, float *right);
    if (fn == NULL) {
        fn = coreSymbol("getSafeAreaInsets");
    }
    fn(top, bottom, left, right);
}

void gamecore_setSafeAreaInsets(float top, float bottom, float left, float right) {
    static void (*fn)(float top, float bottom, float left, float right);
    if (fn == NULL) {
        fn = coreSymbol("setSafeAreaInsets");
    }
    fn(top, bottom, left, right);
}

bool gamecore_consumeSafeAreaInsetsChanged(void) {
    static bool (*fn)(void);
    if (fn == NULL) {
        fn = coreSymbol("consumeSafeAreaInsetsChanged");
    }
    return fn();
}

void gamecore_setHostViewportRegion(float x, float y, float w, float h, bool isPortrait) {
    static void (*fn)(float x, float y, float w, float h, bool isPortrait);
    if (fn == NULL) {
        fn = coreSymbol("setHostViewportRegion");
    }
    fn(x, y, w, h, isPortrait);
}

void gamecore_clearHostViewportRegion(void) {
    static void (*fn)(void);
    if (fn == NULL) {
        fn = coreSymbol("clearHostViewportRegion");
    }
    fn();
}

bool gamecore_getHostViewportRegion(float *x, float *y, float *w, float *h, bool *isPortrait) {
    static bool (*fn)(float *x, float *y, float *w, float *h, bool *isPortrait);
    if (fn == NULL) {
        fn = coreSymbol("getHostViewportRegion");
    }
    return fn(x, y, w, h, isPortrait);
}

float gamecore_getScreenScale(void) {
    static float (*fn)(void);
    if (fn == NULL) {
        fn = coreSymbol("getScreenScale");
    }
    return fn();
}

void *gamecore_getSDLUIKitWindow(void) {
    static void *(*fn)(void);
    if (fn == NULL) {
        fn = coreSymbol("getSDLUIKitWindow");
    }
    return fn();
}

void gamecore_applyPerGameSettings(GameCoreVerticalAlignment verticalAlignment, bool postloadEnabled) {
    static void (*fn)(GameCoreVerticalAlignment verticalAlignment, bool postloadEnabled);
    if (fn == NULL) {
        fn = coreSymbol("applyPerGameSettings");
    }
    fn(verticalAlignment, postloadEnabled);
}

GameCoreVerticalAlignment gamecore_getVerticalAlignment(void) {
    static GameCoreVerticalAlignment (*fn)(void);
    if (fn == NULL) {
        fn = coreSymbol("getVerticalAlignment");
    }
    return fn();
}

bool gamecore_getPostloadEnabled(void) {
    static bool (*fn)(void);
    if (fn == NULL) {
        fn = coreSymbol("getPostloadEnabled");
    }
    return fn();
}

void gamecore_setSyntaxTransformMode(GameCoreSyntaxTransformMode mode) {
    static void (*fn)(GameCoreSyntaxTransformMode mode);
    if (fn == NULL) {
        fn = coreSymbol("setSyntaxTransformMode");
    }
    fn(mode);
}

GameCoreSyntaxTransformMode gamecore_getSyntaxTransformMode(void) {
    static GameCoreSyntaxTransformMode (*fn)(void);
    if (fn == NULL) {
        fn = coreSymbol("getSyntaxTransformMode");
    }
    return fn();
}

void gamecore_setActiveRubyVersion(GameCoreRubyVersion version) {
    static void (*fn)(GameCoreRubyVersion version);
    if (fn == NULL) {
        fn = coreSymbol("setActiveRubyVersion");
    }
    fn(version);
}

GameCoreRubyVersion gamecore_getActiveRubyVersion(void) {
    static GameCoreRubyVersion (*fn)(void);
    if (fn == NULL) {
        fn = coreSymbol("getActiveRubyVersion");
    }
    return fn();
}

void gamecore_applySessionConfig(const GameCoreSessionConfig *config) {
    static void (*fn)(const GameCoreSessionConfig *config);
    if (fn == NULL) {
        fn = coreSymbol("applySessionConfig");
    }
    fn(config);
}

void gamecore_setUseInGameKeyboard(bool enabled) {
    static void (*fn)(bool enabled);
    if (fn == NULL) {
        fn = coreSymbol("setUseInGameKeyboard");
    }
    fn(enabled);
}

bool gamecore_getUseInGameKeyboard(void) {
    static bool (*fn)(void);
    if (fn == NULL) {
        fn = coreSymbol("getUseInGameKeyboard");
    }
    return fn();
}

void gamecore_setJoiplayCompat(bool enabled) {
    static void (*fn)(bool enabled);
    if (fn == NULL) {
        fn = coreSymbol("setJoiplayCompat");
    }
    fn(enabled);
}

bool gamecore_getJoiplayCompat(void) {
    static bool (*fn)(void);
    if (fn == NULL) {
        fn = coreSymbol("getJoiplayCompat");
    }
    return fn();
}

void gamecore_setNetworkEnabled(bool enabled) {
    static void (*fn)(bool enabled);
    if (fn == NULL) {
        fn = coreSymbol("setNetworkEnabled");
    }
    fn(enabled);
}

bool gamecore_getNetworkEnabled(void) {
    static bool (*fn)(void);
    if (fn == NULL) {
        fn = coreSymbol("getNetworkEnabled");
    }
    return fn();
}

void gamecore_setShowViewportBounds(bool enabled) {
    static void (*fn)(bool enabled);
    if (fn == NULL) {
        fn = coreSymbol("setShowViewportBounds");
    }
    fn(enabled);
}

bool gamecore_getShowViewportBounds(void) {
    static bool (*fn)(void);
    if (fn == NULL) {
        fn = coreSymbol("getShowViewportBounds");
    }
    return fn();
}

void gamecore_setCheatsEnabled(bool enabled) {
    static void (*fn)(bool enabled);
    if (fn == NULL) {
        fn = coreSymbol("setCheatsEnabled");
    }
    fn(enabled);
}

bool gamecore_getCheatsEnabled(void) {
    static bool (*fn)(void);
    if (fn == NULL) {
        fn = coreSymbol("getCheatsEnabled");
    }
    return fn();
}

void gamecore_setGameControllerCaptureEnabled(bool enabled) {
    static void (*fn)(bool enabled);
    if (fn == NULL) {
        fn = coreSymbol("setGameControllerCaptureEnabled");
    }
    fn(enabled);
}

bool gamecore_getGameControllerCaptureEnabled(void) {
    static bool (*fn)(void);
    if (fn == NULL) {
        fn = coreSymbol("getGameControllerCaptureEnabled");
    }
    return fn();
}

void gamecore_setTouchMouseEnabled(bool enabled) {
    static void (*fn)(bool enabled);
    if (fn == NULL) {
        fn = coreSymbol("setTouchMouseEnabled");
    }
    fn(enabled);
}

bool gamecore_getTouchMouseEnabled(void) {
    static bool (*fn)(void);
    if (fn == NULL) {
        fn = coreSymbol("getTouchMouseEnabled");
    }
    return fn();
}

void gamecore_setViewportBoundsColor(float r, float g, float b, float a) {
    static void (*fn)(float r, float g, float b, float a);
    if (fn == NULL) {
        fn = coreSymbol("setViewportBoundsColor");
    }
    fn(r, g, b, a);
}

void gamecore_getViewportBoundsColor(float *r, float *g, float *b, float *a) {
    static void (*fn)(float *r, float *g, float *b, float *a);
    if (fn == NULL) {
        fn = coreSymbol("getViewportBoundsColor");
    }
    fn(r, g, b, a);
}

void gamecore_setErrorMessage(const char *message) {
    static void (*fn)(const char *message);
    if (fn == NULL) {
        fn = coreSymbol("setErrorMessage");
    }
    fn(message);
}

void gamecore_presentErrorAndWait(const char *message) {
    static void (*fn)(const char *message);
    if (fn == NULL) {
        fn = coreSymbol("presentErrorAndWait");
    }
    fn(message);
}

void gamecore_signalErrorDismissed(void) {
    static void (*fn)(void);
    if (fn == NULL) {
        fn = coreSymbol("signalErrorDismissed");
    }
    fn();
}

void gamecore_reportFatalError(const char *message) {
    static void (*fn)(const char *message);
    if (fn == NULL) {
        fn = coreSymbol("reportFatalError");
    }
    fn(message);
}

void gamecore_installFatalErrorHandlers(void) {
    static void (*fn)(void);
    if (fn == NULL) {
        fn = coreSymbol("installFatalErrorHandlers");
    }
    fn();
}

void gamecore_setErrorMessageCallback(gamecore_ErrorMessageCallback cb, void *userdata) {
    static void (*fn)(gamecore_ErrorMessageCallback cb, void *userdata);
    if (fn == NULL) {
        fn = coreSymbol("setErrorMessageCallback");
    }
    fn(cb, userdata);
}

void gamecore_presentInfoAndWait(const char *message) {
    static void (*fn)(const char *message);
    if (fn == NULL) {
        fn = coreSymbol("presentInfoAndWait");
    }
    fn(message);
}

void gamecore_signalInfoDismissed(void) {
    static void (*fn)(void);
    if (fn == NULL) {
        fn = coreSymbol("signalInfoDismissed");
    }
    fn();
}

void gamecore_setInfoMessageCallback(gamecore_InfoMessageCallback cb, void *userdata) {
    static void (*fn)(gamecore_InfoMessageCallback cb, void *userdata);
    if (fn == NULL) {
        fn = coreSymbol("setInfoMessageCallback");
    }
    fn(cb, userdata);
}

void gamecore_requestPause(void) {
    static void (*fn)(void);
    if (fn == NULL) {
        fn = coreSymbol("requestPause");
    }
    fn();
}

void gamecore_requestResume(void) {
    static void (*fn)(void);
    if (fn == NULL) {
        fn = coreSymbol("requestResume");
    }
    fn();
}

void gamecore_checkPause(void) {
    static void (*fn)(void);
    if (fn == NULL) {
        fn = coreSymbol("checkPause");
    }
    fn();
}

bool gamecore_isPauseRequested(void) {
    static bool (*fn)(void);
    if (fn == NULL) {
        fn = coreSymbol("isPauseRequested");
    }
    return fn();
}

bool gamecore_isPaused(void) {
    static bool (*fn)(void);
    if (fn == NULL) {
        fn = coreSymbol("isPaused");
    }
    return fn();
}

void gamecore_setSnapshot(const unsigned char *data, int width, int height) {
    static void (*fn)(const unsigned char *data, int width, int height);
    if (fn == NULL) {
        fn = coreSymbol("setSnapshot");
    }
    fn(data, width, height);
}

bool gamecore_copySnapshotRGBA(unsigned char *dest, int destSize, int *width, int *height) {
    static bool (*fn)(unsigned char *dest, int destSize, int *width, int *height);
    if (fn == NULL) {
        fn = coreSymbol("copySnapshotRGBA");
    }
    return fn(dest, destSize, width, height);
}

bool gamecore_getSnapshotSize(int *width, int *height) {
    static bool (*fn)(int *width, int *height);
    if (fn == NULL) {
        fn = coreSymbol("getSnapshotSize");
    }
    return fn(width, height);
}

void gamecore_setPausedCallback(gamecore_PausedCallback cb, void *userdata) {
    static void (*fn)(gamecore_PausedCallback cb, void *userdata);
    if (fn == NULL) {
        fn = coreSymbol("setPausedCallback");
    }
    fn(cb, userdata);
}

void gamecore_setResumedCallback(gamecore_ResumedCallback cb, void *userdata) {
    static void (*fn)(gamecore_ResumedCallback cb, void *userdata);
    if (fn == NULL) {
        fn = coreSymbol("setResumedCallback");
    }
    fn(cb, userdata);
}

void gamecore_setFrameRenderedCallback(gamecore_FrameRenderedCallback cb, void *userdata) {
    static void (*fn)(gamecore_FrameRenderedCallback cb, void *userdata);
    if (fn == NULL) {
        fn = coreSymbol("setFrameRenderedCallback");
    }
    fn(cb, userdata);
}

void gamecore_signalFrameRendered(void) {
    static void (*fn)(void);
    if (fn == NULL) {
        fn = coreSymbol("signalFrameRendered");
    }
    fn();
}

void gamecore_setGLContextBroken(void) {
    static void (*fn)(void);
    if (fn == NULL) {
        fn = coreSymbol("setGLContextBroken");
    }
    fn();
}

bool gamecore_isGLContextBroken(void) {
    static bool (*fn)(void);
    if (fn == NULL) {
        fn = coreSymbol("isGLContextBroken");
    }
    return fn();
}

void gamecore_setFastForwardMultiplier(int multiplier) {
    static void (*fn)(int multiplier);
    if (fn == NULL) {
        fn = coreSymbol("setFastForwardMultiplier");
    }
    fn(multiplier);
}

int gamecore_getFastForwardMultiplier(void) {
    static int (*fn)(void);
    if (fn == NULL) {
        fn = coreSymbol("getFastForwardMultiplier");
    }
    return fn();
}

void gamecore_resetSessionState(void) {
    static void (*fn)(void);
    if (fn == NULL) {
        fn = coreSymbol("resetSessionState");
    }
    fn();
}

void gamecore_setDebugLogPath(const char *path) {
    static void (*fn)(const char *path);
    if (fn == NULL) {
        fn = coreSymbol("setDebugLogPath");
    }
    fn(path);
}

void gamecore_debugLog(const char *tag, const char *source, const char *message) {
    static void (*fn)(const char *tag, const char *source, const char *message);
    if (fn == NULL) {
        fn = coreSymbol("debugLog");
    }
    fn(tag, source, message);
}

int gamecore_debugLogEnabled(void) {
    static int (*fn)(void);
    if (fn == NULL) {
        fn = coreSymbol("debugLogEnabled");
    }
    return fn();
}
