// Generated by tools/mkxp-core/generate-core-forwarders.sh from
// mkxp-z-apple-mobile/src/app_bridge.h. Do not edit by hand.

#include "EmpoCore.h"

#include <dlfcn.h>
#include <stdio.h>
#include <stdlib.h>

#include "app_bridge.h"

static void *gCore;

int EmpoCoreOpen(const char *binaryPath) {
    if (gCore != NULL) {
        return 1;
    }
    // RTLD_LOCAL keeps the core's names out of the global namespace, so
    // a second core opened later cannot bind to them. Every mkxp_* name
    // below reaches this image through its own handle.
    gCore = dlopen(binaryPath, RTLD_NOW | RTLD_LOCAL);
    if (gCore == NULL) {
        fprintf(stderr, "EmpoCore: cannot open %s: %s\n", binaryPath, dlerror());
        return 0;
    }
    return 1;
}

int EmpoCoreIsOpen(void) {
    return gCore != NULL;
}

static void *coreSymbol(const char *name) {
    void *address = gCore != NULL ? dlsym(gCore, name) : NULL;
    if (address == NULL) {
        // Either the app called the engine before it picked a game, or
        // the framework and this file were built from different
        // headers. Both are build errors, and a silent no-op would hide
        // them until a game misbehaved.
        fprintf(stderr, "EmpoCore: %s is not available (core open: %d)\n", name, gCore != NULL);
        abort();
    }
    return address;
}

int mkxp_run_app(int argc, char **argv) {
    static int (*fn)(int argc, char **argv);
    if (fn == NULL) {
        fn = coreSymbol("mkxp_run_app");
    }
    return fn(argc, argv);
}

void mkxp_setGameReady(void) {
    static void (*fn)(void);
    if (fn == NULL) {
        fn = coreSymbol("mkxp_setGameReady");
    }
    fn();
}

int mkxp_isGameReady(void) {
    static int (*fn)(void);
    if (fn == NULL) {
        fn = coreSymbol("mkxp_isGameReady");
    }
    return fn();
}

void mkxp_setGamePath(const char *path) {
    static void (*fn)(const char *path);
    if (fn == NULL) {
        fn = coreSymbol("mkxp_setGamePath");
    }
    fn(path);
}

const char *mkxp_waitForGamePath(void) {
    static const char *(*fn)(void);
    if (fn == NULL) {
        fn = coreSymbol("mkxp_waitForGamePath");
    }
    return fn();
}

void mkxp_requestTerminate(void) {
    static void (*fn)(void);
    if (fn == NULL) {
        fn = coreSymbol("mkxp_requestTerminate");
    }
    fn();
}

int mkxp_isEngineTerminated(void) {
    static int (*fn)(void);
    if (fn == NULL) {
        fn = coreSymbol("mkxp_isEngineTerminated");
    }
    return fn();
}

void mkxp_setEngineTerminated(void) {
    static void (*fn)(void);
    if (fn == NULL) {
        fn = coreSymbol("mkxp_setEngineTerminated");
    }
    fn();
}

int mkxp_didEngineExitCleanly(void) {
    static int (*fn)(void);
    if (fn == NULL) {
        fn = coreSymbol("mkxp_didEngineExitCleanly");
    }
    return fn();
}

void mkxp_setEngineExitedCleanly(void) {
    static void (*fn)(void);
    if (fn == NULL) {
        fn = coreSymbol("mkxp_setEngineExitedCleanly");
    }
    fn();
}

int mkxp_isEngineHung(void) {
    static int (*fn)(void);
    if (fn == NULL) {
        fn = coreSymbol("mkxp_isEngineHung");
    }
    return fn();
}

void mkxp_setEngineHung(void) {
    static void (*fn)(void);
    if (fn == NULL) {
        fn = coreSymbol("mkxp_setEngineHung");
    }
    fn();
}

void mkxp_setEngineTerminatedCallback(mkxp_EngineTerminatedCallback cb, void *userdata) {
    static void (*fn)(mkxp_EngineTerminatedCallback cb, void *userdata);
    if (fn == NULL) {
        fn = coreSymbol("mkxp_setEngineTerminatedCallback");
    }
    fn(cb, userdata);
}

void mkxp_setGameRectChangedCallback(mkxp_GameRectChangedCallback cb, void *userdata) {
    static void (*fn)(mkxp_GameRectChangedCallback cb, void *userdata);
    if (fn == NULL) {
        fn = coreSymbol("mkxp_setGameRectChangedCallback");
    }
    fn(cb, userdata);
}

void mkxp_injectKeyEvent(int scancode, int pressed) {
    static void (*fn)(int scancode, int pressed);
    if (fn == NULL) {
        fn = coreSymbol("mkxp_injectKeyEvent");
    }
    fn(scancode, pressed);
}

void mkxp_setKeyEventCallback(mkxp_KeyEventCallback cb, void *userdata) {
    static void (*fn)(mkxp_KeyEventCallback cb, void *userdata);
    if (fn == NULL) {
        fn = coreSymbol("mkxp_setKeyEventCallback");
    }
    fn(cb, userdata);
}

void mkxp_injectPointerEvent(int x, int y, MKXPPointerPhase phase) {
    static void (*fn)(int x, int y, MKXPPointerPhase phase);
    if (fn == NULL) {
        fn = coreSymbol("mkxp_injectPointerEvent");
    }
    fn(x, y, phase);
}

void mkxp_setManagedConfigDir(const char *path) {
    static void (*fn)(const char *path);
    if (fn == NULL) {
        fn = coreSymbol("mkxp_setManagedConfigDir");
    }
    fn(path);
}

const char *mkxp_getManagedConfigDir(void) {
    static const char *(*fn)(void);
    if (fn == NULL) {
        fn = coreSymbol("mkxp_getManagedConfigDir");
    }
    return fn();
}

void mkxp_setConfigOverlayJSON(const char *jsonUTF8) {
    static void (*fn)(const char *jsonUTF8);
    if (fn == NULL) {
        fn = coreSymbol("mkxp_setConfigOverlayJSON");
    }
    fn(jsonUTF8);
}

const char *mkxp_getConfigOverlayJSON(void) {
    static const char *(*fn)(void);
    if (fn == NULL) {
        fn = coreSymbol("mkxp_getConfigOverlayJSON");
    }
    return fn();
}

void mkxp_setUserDataDirectory(const char *path) {
    static void (*fn)(const char *path);
    if (fn == NULL) {
        fn = coreSymbol("mkxp_setUserDataDirectory");
    }
    fn(path);
}

const char *mkxp_getUserDataDirectory(void) {
    static const char *(*fn)(void);
    if (fn == NULL) {
        fn = coreSymbol("mkxp_getUserDataDirectory");
    }
    return fn();
}

void mkxp_setSharedFontsDirectory(const char *path) {
    static void (*fn)(const char *path);
    if (fn == NULL) {
        fn = coreSymbol("mkxp_setSharedFontsDirectory");
    }
    fn(path);
}

const char *mkxp_getSharedFontsDirectory(void) {
    static const char *(*fn)(void);
    if (fn == NULL) {
        fn = coreSymbol("mkxp_getSharedFontsDirectory");
    }
    return fn();
}

void mkxp_setLauncherIdentity(const char *name) {
    static void (*fn)(const char *name);
    if (fn == NULL) {
        fn = coreSymbol("mkxp_setLauncherIdentity");
    }
    fn(name);
}

const char *mkxp_getLauncherIdentity(void) {
    static const char *(*fn)(void);
    if (fn == NULL) {
        fn = coreSymbol("mkxp_getLauncherIdentity");
    }
    return fn();
}

void mkxp_setCABundlePath(const char *path) {
    static void (*fn)(const char *path);
    if (fn == NULL) {
        fn = coreSymbol("mkxp_setCABundlePath");
    }
    fn(path);
}

const char *mkxp_getCABundlePath(void) {
    static const char *(*fn)(void);
    if (fn == NULL) {
        fn = coreSymbol("mkxp_getCABundlePath");
    }
    return fn();
}

void mkxp_setTextInputModeCallback(mkxp_TextInputModeCallback cb, void *userdata) {
    static void (*fn)(mkxp_TextInputModeCallback cb, void *userdata);
    if (fn == NULL) {
        fn = coreSymbol("mkxp_setTextInputModeCallback");
    }
    fn(cb, userdata);
}

void mkxp_pushTextInput(const char *utf8) {
    static void (*fn)(const char *utf8);
    if (fn == NULL) {
        fn = coreSymbol("mkxp_pushTextInput");
    }
    fn(utf8);
}

int mkxp_isTextInputActive(void) {
    static int (*fn)(void);
    if (fn == NULL) {
        fn = coreSymbol("mkxp_isTextInputActive");
    }
    return fn();
}

double mkxp_getAverageFPS(void) {
    static double (*fn)(void);
    if (fn == NULL) {
        fn = coreSymbol("mkxp_getAverageFPS");
    }
    return fn();
}

int mkxp_getTargetFPS(void) {
    static int (*fn)(void);
    if (fn == NULL) {
        fn = coreSymbol("mkxp_getTargetFPS");
    }
    return fn();
}

int mkxp_getRGSSVersion(void) {
    static int (*fn)(void);
    if (fn == NULL) {
        fn = coreSymbol("mkxp_getRGSSVersion");
    }
    return fn();
}

const char *mkxp_getGameTitle(void) {
    static const char *(*fn)(void);
    if (fn == NULL) {
        fn = coreSymbol("mkxp_getGameTitle");
    }
    return fn();
}

int mkxp_getSupportedRGSSVersionMask(void) {
    static int (*fn)(void);
    if (fn == NULL) {
        fn = coreSymbol("mkxp_getSupportedRGSSVersionMask");
    }
    return fn();
}

const char *mkxp_getRubyVersion(void) {
    static const char *(*fn)(void);
    if (fn == NULL) {
        fn = coreSymbol("mkxp_getRubyVersion");
    }
    return fn();
}

const char *mkxp_getANGLEVersion(void) {
    static const char *(*fn)(void);
    if (fn == NULL) {
        fn = coreSymbol("mkxp_getANGLEVersion");
    }
    return fn();
}

const char *mkxp_getMetalDeviceName(void) {
    static const char *(*fn)(void);
    if (fn == NULL) {
        fn = coreSymbol("mkxp_getMetalDeviceName");
    }
    return fn();
}

void mkxp_setGameRect(float x, float y, float w, float h) {
    static void (*fn)(float x, float y, float w, float h);
    if (fn == NULL) {
        fn = coreSymbol("mkxp_setGameRect");
    }
    fn(x, y, w, h);
}

void mkxp_getSafeAreaInsets(float *top, float *bottom, float *left, float *right) {
    static void (*fn)(float *top, float *bottom, float *left, float *right);
    if (fn == NULL) {
        fn = coreSymbol("mkxp_getSafeAreaInsets");
    }
    fn(top, bottom, left, right);
}

void mkxp_setSafeAreaInsets(float top, float bottom, float left, float right) {
    static void (*fn)(float top, float bottom, float left, float right);
    if (fn == NULL) {
        fn = coreSymbol("mkxp_setSafeAreaInsets");
    }
    fn(top, bottom, left, right);
}

bool mkxp_consumeSafeAreaInsetsChanged(void) {
    static bool (*fn)(void);
    if (fn == NULL) {
        fn = coreSymbol("mkxp_consumeSafeAreaInsetsChanged");
    }
    return fn();
}

void mkxp_setHostViewportRegion(float x, float y, float w, float h, bool isPortrait) {
    static void (*fn)(float x, float y, float w, float h, bool isPortrait);
    if (fn == NULL) {
        fn = coreSymbol("mkxp_setHostViewportRegion");
    }
    fn(x, y, w, h, isPortrait);
}

void mkxp_clearHostViewportRegion(void) {
    static void (*fn)(void);
    if (fn == NULL) {
        fn = coreSymbol("mkxp_clearHostViewportRegion");
    }
    fn();
}

bool mkxp_getHostViewportRegion(float *x, float *y, float *w, float *h, bool *isPortrait) {
    static bool (*fn)(float *x, float *y, float *w, float *h, bool *isPortrait);
    if (fn == NULL) {
        fn = coreSymbol("mkxp_getHostViewportRegion");
    }
    return fn(x, y, w, h, isPortrait);
}

float mkxp_getScreenScale(void) {
    static float (*fn)(void);
    if (fn == NULL) {
        fn = coreSymbol("mkxp_getScreenScale");
    }
    return fn();
}

void *mkxp_getSDLUIKitWindow(void) {
    static void *(*fn)(void);
    if (fn == NULL) {
        fn = coreSymbol("mkxp_getSDLUIKitWindow");
    }
    return fn();
}

void mkxp_applyPerGameSettings(MKXPVerticalAlignment verticalAlignment, bool postloadEnabled) {
    static void (*fn)(MKXPVerticalAlignment verticalAlignment, bool postloadEnabled);
    if (fn == NULL) {
        fn = coreSymbol("mkxp_applyPerGameSettings");
    }
    fn(verticalAlignment, postloadEnabled);
}

MKXPVerticalAlignment mkxp_getVerticalAlignment(void) {
    static MKXPVerticalAlignment (*fn)(void);
    if (fn == NULL) {
        fn = coreSymbol("mkxp_getVerticalAlignment");
    }
    return fn();
}

bool mkxp_getPostloadEnabled(void) {
    static bool (*fn)(void);
    if (fn == NULL) {
        fn = coreSymbol("mkxp_getPostloadEnabled");
    }
    return fn();
}

void mkxp_setSyntaxTransformMode(MKXPSyntaxTransformMode mode) {
    static void (*fn)(MKXPSyntaxTransformMode mode);
    if (fn == NULL) {
        fn = coreSymbol("mkxp_setSyntaxTransformMode");
    }
    fn(mode);
}

MKXPSyntaxTransformMode mkxp_getSyntaxTransformMode(void) {
    static MKXPSyntaxTransformMode (*fn)(void);
    if (fn == NULL) {
        fn = coreSymbol("mkxp_getSyntaxTransformMode");
    }
    return fn();
}

void mkxp_setActiveRubyVersion(MKXPRubyVersion version) {
    static void (*fn)(MKXPRubyVersion version);
    if (fn == NULL) {
        fn = coreSymbol("mkxp_setActiveRubyVersion");
    }
    fn(version);
}

MKXPRubyVersion mkxp_getActiveRubyVersion(void) {
    static MKXPRubyVersion (*fn)(void);
    if (fn == NULL) {
        fn = coreSymbol("mkxp_getActiveRubyVersion");
    }
    return fn();
}

void mkxp_applySessionConfig(const MKXPSessionConfig *config) {
    static void (*fn)(const MKXPSessionConfig *config);
    if (fn == NULL) {
        fn = coreSymbol("mkxp_applySessionConfig");
    }
    fn(config);
}

void mkxp_setUseInGameKeyboard(bool enabled) {
    static void (*fn)(bool enabled);
    if (fn == NULL) {
        fn = coreSymbol("mkxp_setUseInGameKeyboard");
    }
    fn(enabled);
}

bool mkxp_getUseInGameKeyboard(void) {
    static bool (*fn)(void);
    if (fn == NULL) {
        fn = coreSymbol("mkxp_getUseInGameKeyboard");
    }
    return fn();
}

void mkxp_setJoiplayCompat(bool enabled) {
    static void (*fn)(bool enabled);
    if (fn == NULL) {
        fn = coreSymbol("mkxp_setJoiplayCompat");
    }
    fn(enabled);
}

bool mkxp_getJoiplayCompat(void) {
    static bool (*fn)(void);
    if (fn == NULL) {
        fn = coreSymbol("mkxp_getJoiplayCompat");
    }
    return fn();
}

void mkxp_setNetworkEnabled(bool enabled) {
    static void (*fn)(bool enabled);
    if (fn == NULL) {
        fn = coreSymbol("mkxp_setNetworkEnabled");
    }
    fn(enabled);
}

bool mkxp_getNetworkEnabled(void) {
    static bool (*fn)(void);
    if (fn == NULL) {
        fn = coreSymbol("mkxp_getNetworkEnabled");
    }
    return fn();
}

void mkxp_setShowViewportBounds(bool enabled) {
    static void (*fn)(bool enabled);
    if (fn == NULL) {
        fn = coreSymbol("mkxp_setShowViewportBounds");
    }
    fn(enabled);
}

bool mkxp_getShowViewportBounds(void) {
    static bool (*fn)(void);
    if (fn == NULL) {
        fn = coreSymbol("mkxp_getShowViewportBounds");
    }
    return fn();
}

void mkxp_setCheatsEnabled(bool enabled) {
    static void (*fn)(bool enabled);
    if (fn == NULL) {
        fn = coreSymbol("mkxp_setCheatsEnabled");
    }
    fn(enabled);
}

bool mkxp_getCheatsEnabled(void) {
    static bool (*fn)(void);
    if (fn == NULL) {
        fn = coreSymbol("mkxp_getCheatsEnabled");
    }
    return fn();
}

void mkxp_setGameControllerCaptureEnabled(bool enabled) {
    static void (*fn)(bool enabled);
    if (fn == NULL) {
        fn = coreSymbol("mkxp_setGameControllerCaptureEnabled");
    }
    fn(enabled);
}

bool mkxp_getGameControllerCaptureEnabled(void) {
    static bool (*fn)(void);
    if (fn == NULL) {
        fn = coreSymbol("mkxp_getGameControllerCaptureEnabled");
    }
    return fn();
}

void mkxp_setTouchMouseEnabled(bool enabled) {
    static void (*fn)(bool enabled);
    if (fn == NULL) {
        fn = coreSymbol("mkxp_setTouchMouseEnabled");
    }
    fn(enabled);
}

bool mkxp_getTouchMouseEnabled(void) {
    static bool (*fn)(void);
    if (fn == NULL) {
        fn = coreSymbol("mkxp_getTouchMouseEnabled");
    }
    return fn();
}

void mkxp_setViewportBoundsColor(float r, float g, float b, float a) {
    static void (*fn)(float r, float g, float b, float a);
    if (fn == NULL) {
        fn = coreSymbol("mkxp_setViewportBoundsColor");
    }
    fn(r, g, b, a);
}

void mkxp_getViewportBoundsColor(float *r, float *g, float *b, float *a) {
    static void (*fn)(float *r, float *g, float *b, float *a);
    if (fn == NULL) {
        fn = coreSymbol("mkxp_getViewportBoundsColor");
    }
    fn(r, g, b, a);
}

void mkxp_setErrorMessage(const char *message) {
    static void (*fn)(const char *message);
    if (fn == NULL) {
        fn = coreSymbol("mkxp_setErrorMessage");
    }
    fn(message);
}

void mkxp_presentErrorAndWait(const char *message) {
    static void (*fn)(const char *message);
    if (fn == NULL) {
        fn = coreSymbol("mkxp_presentErrorAndWait");
    }
    fn(message);
}

void mkxp_signalErrorDismissed(void) {
    static void (*fn)(void);
    if (fn == NULL) {
        fn = coreSymbol("mkxp_signalErrorDismissed");
    }
    fn();
}

void mkxp_reportFatalError(const char *message) {
    static void (*fn)(const char *message);
    if (fn == NULL) {
        fn = coreSymbol("mkxp_reportFatalError");
    }
    fn(message);
}

void mkxp_installFatalErrorHandlers(void) {
    static void (*fn)(void);
    if (fn == NULL) {
        fn = coreSymbol("mkxp_installFatalErrorHandlers");
    }
    fn();
}

void mkxp_setErrorMessageCallback(mkxp_ErrorMessageCallback cb, void *userdata) {
    static void (*fn)(mkxp_ErrorMessageCallback cb, void *userdata);
    if (fn == NULL) {
        fn = coreSymbol("mkxp_setErrorMessageCallback");
    }
    fn(cb, userdata);
}

void mkxp_presentInfoAndWait(const char *message) {
    static void (*fn)(const char *message);
    if (fn == NULL) {
        fn = coreSymbol("mkxp_presentInfoAndWait");
    }
    fn(message);
}

void mkxp_signalInfoDismissed(void) {
    static void (*fn)(void);
    if (fn == NULL) {
        fn = coreSymbol("mkxp_signalInfoDismissed");
    }
    fn();
}

void mkxp_setInfoMessageCallback(mkxp_InfoMessageCallback cb, void *userdata) {
    static void (*fn)(mkxp_InfoMessageCallback cb, void *userdata);
    if (fn == NULL) {
        fn = coreSymbol("mkxp_setInfoMessageCallback");
    }
    fn(cb, userdata);
}

void mkxp_requestPause(void) {
    static void (*fn)(void);
    if (fn == NULL) {
        fn = coreSymbol("mkxp_requestPause");
    }
    fn();
}

void mkxp_requestResume(void) {
    static void (*fn)(void);
    if (fn == NULL) {
        fn = coreSymbol("mkxp_requestResume");
    }
    fn();
}

void mkxp_checkPause(void) {
    static void (*fn)(void);
    if (fn == NULL) {
        fn = coreSymbol("mkxp_checkPause");
    }
    fn();
}

bool mkxp_isPauseRequested(void) {
    static bool (*fn)(void);
    if (fn == NULL) {
        fn = coreSymbol("mkxp_isPauseRequested");
    }
    return fn();
}

bool mkxp_isPaused(void) {
    static bool (*fn)(void);
    if (fn == NULL) {
        fn = coreSymbol("mkxp_isPaused");
    }
    return fn();
}

void mkxp_setSnapshot(const unsigned char *data, int width, int height) {
    static void (*fn)(const unsigned char *data, int width, int height);
    if (fn == NULL) {
        fn = coreSymbol("mkxp_setSnapshot");
    }
    fn(data, width, height);
}

bool mkxp_copySnapshotRGBA(unsigned char *dest, int destSize, int *width, int *height) {
    static bool (*fn)(unsigned char *dest, int destSize, int *width, int *height);
    if (fn == NULL) {
        fn = coreSymbol("mkxp_copySnapshotRGBA");
    }
    return fn(dest, destSize, width, height);
}

bool mkxp_getSnapshotSize(int *width, int *height) {
    static bool (*fn)(int *width, int *height);
    if (fn == NULL) {
        fn = coreSymbol("mkxp_getSnapshotSize");
    }
    return fn(width, height);
}

void mkxp_setPausedCallback(mkxp_PausedCallback cb, void *userdata) {
    static void (*fn)(mkxp_PausedCallback cb, void *userdata);
    if (fn == NULL) {
        fn = coreSymbol("mkxp_setPausedCallback");
    }
    fn(cb, userdata);
}

void mkxp_setResumedCallback(mkxp_ResumedCallback cb, void *userdata) {
    static void (*fn)(mkxp_ResumedCallback cb, void *userdata);
    if (fn == NULL) {
        fn = coreSymbol("mkxp_setResumedCallback");
    }
    fn(cb, userdata);
}

void mkxp_setFrameRenderedCallback(mkxp_FrameRenderedCallback cb, void *userdata) {
    static void (*fn)(mkxp_FrameRenderedCallback cb, void *userdata);
    if (fn == NULL) {
        fn = coreSymbol("mkxp_setFrameRenderedCallback");
    }
    fn(cb, userdata);
}

void mkxp_signalFrameRendered(void) {
    static void (*fn)(void);
    if (fn == NULL) {
        fn = coreSymbol("mkxp_signalFrameRendered");
    }
    fn();
}

void mkxp_setGLContextBroken(void) {
    static void (*fn)(void);
    if (fn == NULL) {
        fn = coreSymbol("mkxp_setGLContextBroken");
    }
    fn();
}

bool mkxp_isGLContextBroken(void) {
    static bool (*fn)(void);
    if (fn == NULL) {
        fn = coreSymbol("mkxp_isGLContextBroken");
    }
    return fn();
}

void mkxp_setFastForwardMultiplier(int multiplier) {
    static void (*fn)(int multiplier);
    if (fn == NULL) {
        fn = coreSymbol("mkxp_setFastForwardMultiplier");
    }
    fn(multiplier);
}

int mkxp_getFastForwardMultiplier(void) {
    static int (*fn)(void);
    if (fn == NULL) {
        fn = coreSymbol("mkxp_getFastForwardMultiplier");
    }
    return fn();
}

void mkxp_resetSessionState(void) {
    static void (*fn)(void);
    if (fn == NULL) {
        fn = coreSymbol("mkxp_resetSessionState");
    }
    fn();
}

void mkxp_setDebugLogPath(const char *path) {
    static void (*fn)(const char *path);
    if (fn == NULL) {
        fn = coreSymbol("mkxp_setDebugLogPath");
    }
    fn(path);
}

void mkxp_debugLog(const char *tag, const char *source, const char *message) {
    static void (*fn)(const char *tag, const char *source, const char *message);
    if (fn == NULL) {
        fn = coreSymbol("mkxp_debugLog");
    }
    fn(tag, source, message);
}

int mkxp_debugLogEnabled(void) {
    static int (*fn)(void);
    if (fn == NULL) {
        fn = coreSymbol("mkxp_debugLogEnabled");
    }
    return fn();
}
