#!/bin/sh
# Setup script for Empo development.
# Run this once after cloning the repository.

set -e

REPO_ROOT="$(cd "$(dirname "$0")" && pwd)"

# Use tracked git hooks (.githooks/) instead of the default .git/hooks/
git -C "$REPO_ROOT" config core.hooksPath .githooks
echo "Git hooks configured."

# Generate initial GitInfo.generated.swift
COMMIT=$(git -C "$REPO_ROOT" rev-parse --short HEAD 2>/dev/null || echo "unknown")
OUT="$REPO_ROOT/ios/Empo/src/App/GitInfo.generated.swift"
cat > "$OUT" <<EOF
// Auto-generated by setup script — do not edit
enum GitInfo {
    static let commit = "$COMMIT"
    static let dirty = false
}
EOF
echo "Generated GitInfo.generated.swift ($COMMIT)."

echo "Done."
