#!/bin/sh
# Generate the C file that lets Empo call the engine through
# MkxpCore.framework without linking it.
#
# Empo opens the core with dlopen and RTLD_LOCAL, so the linker cannot
# resolve a single mkxp_* name at build time. This writes one forwarder
# for every function app_bridge.h declares. Each forwarder looks its
# symbol up in the open core on first use, so every Swift and ObjC call
# site stays as it is.
#
# The list comes from the header, and the framework's export list comes
# from the same header (build-framework-ios.sh), so the two cannot
# drift.
#
# Usage:
#   tools/mkxp-core/generate-core-forwarders.sh [--out <file>]
set -eu

ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
HEADER="$ROOT/mkxp-z-apple-mobile/src/app_bridge.h"
OUT="$ROOT/ios/Empo/src/App/MkxpCoreForwarders.c"

while [ "$#" -gt 0 ]; do
    case "$1" in
        --out)
            OUT="$2"
            shift 2
            ;;
        *)
            echo "generate-core-forwarders: unknown argument $1" >&2
            exit 2
            ;;
    esac
done

[ -f "$HEADER" ] || {
    echo "generate-core-forwarders: $HEADER missing" >&2
    exit 1
}

TMP="$(mktemp "${TMPDIR:-/tmp}/mkxp-forwarders.XXXXXX")"
trap 'rm -f "$TMP"' EXIT

cat >"$TMP" <<'HEAD'
// Generated by tools/mkxp-core/generate-core-forwarders.sh from
// mkxp-z-apple-mobile/src/app_bridge.h. Do not edit by hand.

#include "EmpoCore.h"

#include <dlfcn.h>
#include <stdio.h>
#include <stdlib.h>

#include "app_bridge.h"

static void *gCore;

int EmpoCoreOpen(const char *binaryPath) {
    if (gCore != NULL) {
        return 1;
    }
    // RTLD_LOCAL keeps the core's names out of the global namespace, so
    // a second core opened later cannot bind to them. Every mkxp_* name
    // below reaches this image through its own handle.
    gCore = dlopen(binaryPath, RTLD_NOW | RTLD_LOCAL);
    if (gCore == NULL) {
        fprintf(stderr, "EmpoCore: cannot open %s: %s\n", binaryPath, dlerror());
        return 0;
    }
    return 1;
}

int EmpoCoreIsOpen(void) { return gCore != NULL; }

static void *coreSymbol(const char *name) {
    void *address = gCore != NULL ? dlsym(gCore, name) : NULL;
    if (address == NULL) {
        // Either the app called the engine before it picked a game, or
        // the framework and this file were built from different
        // headers. Both are build errors, and a silent no-op would hide
        // them until a game misbehaved.
        fprintf(stderr, "EmpoCore: %s is not available (core open: %d)\n", name,
                gCore != NULL);
        abort();
    }
    return address;
}

HEAD

awk -f "$ROOT/tools/mkxp-core/forwarders.awk" "$HEADER" >>"$TMP"

COUNT="$(grep -c '^    if (fn == NULL) {' "$TMP")"
if [ "$COUNT" -lt 80 ]; then
    echo "generate-core-forwarders: only $COUNT forwarders parsed, refusing" >&2
    exit 1
fi

mkdir -p "$(dirname "$OUT")"
mv "$TMP" "$OUT"
trap - EXIT
echo "generate-core-forwarders: wrote $COUNT forwarders to $OUT"
