// Generated by tools/gamecore/generate-core-forwarders.sh from
// cores/GameCore.h. Do not edit by hand.

#include "EmpoCore.h"

#include <dlfcn.h>
#include <stdio.h>
#include <stdlib.h>

#include "GameCore.h"

static void *gCore;

int EmpoCoreOpen(const char *binaryPath) {
    if (gCore != NULL) {
        fprintf(stderr, "EmpoCore: a core is open, refusing %s\n", binaryPath);
        return 0;
    }
    // RTLD_LOCAL keeps the core's names out of the global namespace.
    // Every name below reaches this image through its own handle.
    void *core = dlopen(binaryPath, RTLD_NOW | RTLD_LOCAL);
    if (core == NULL) {
        fprintf(stderr, "EmpoCore: cannot open %s: %s\n", binaryPath, dlerror());
        return 0;
    }
    gCore = core;
    return 1;
}

// dlsym with the core's handle searches that image only, so the core
// answers under the same name without a clash with the forwarder below.
static void *coreSymbol(const char *symbol) {
    void *address = gCore != NULL ? dlsym(gCore, symbol) : NULL;
    if (address == NULL) {
        // Either the process called the core before it opened one, or
        // the framework and this file were built from different
        // headers. Both are build errors, and a silent no-op would hide
        // them until a game misbehaved.
        fprintf(stderr, "EmpoCore: %s is not available (core open: %d)\n", symbol, gCore != NULL);
        abort();
    }
    return address;
}

int gamecore_run_app(int argc, char **argv) {
    static int (*fn)(int argc, char **argv);
    if (fn == NULL) {
        fn = coreSymbol("gamecore_run_app");
    }
    return fn(argc, argv);
}

int gamecore_isGameReady(void) {
    static int (*fn)(void);
    if (fn == NULL) {
        fn = coreSymbol("gamecore_isGameReady");
    }
    return fn();
}

void gamecore_setGamePath(const char *path) {
    static void (*fn)(const char *path);
    if (fn == NULL) {
        fn = coreSymbol("gamecore_setGamePath");
    }
    fn(path);
}

int gamecore_isEngineTerminated(void) {
    static int (*fn)(void);
    if (fn == NULL) {
        fn = coreSymbol("gamecore_isEngineTerminated");
    }
    return fn();
}

int gamecore_didEngineExitCleanly(void) {
    static int (*fn)(void);
    if (fn == NULL) {
        fn = coreSymbol("gamecore_didEngineExitCleanly");
    }
    return fn();
}

int gamecore_isEngineHung(void) {
    static int (*fn)(void);
    if (fn == NULL) {
        fn = coreSymbol("gamecore_isEngineHung");
    }
    return fn();
}

void gamecore_setEngineTerminatedCallback(gamecore_EngineTerminatedCallback cb, void *userdata) {
    static void (*fn)(gamecore_EngineTerminatedCallback cb, void *userdata);
    if (fn == NULL) {
        fn = coreSymbol("gamecore_setEngineTerminatedCallback");
    }
    fn(cb, userdata);
}

void gamecore_setGameRectChangedCallback(gamecore_GameRectChangedCallback cb, void *userdata) {
    static void (*fn)(gamecore_GameRectChangedCallback cb, void *userdata);
    if (fn == NULL) {
        fn = coreSymbol("gamecore_setGameRectChangedCallback");
    }
    fn(cb, userdata);
}

void gamecore_injectKeyEvent(int scancode, int pressed) {
    static void (*fn)(int scancode, int pressed);
    if (fn == NULL) {
        fn = coreSymbol("gamecore_injectKeyEvent");
    }
    fn(scancode, pressed);
}

void gamecore_setLauncherIdentity(const char *name) {
    static void (*fn)(const char *name);
    if (fn == NULL) {
        fn = coreSymbol("gamecore_setLauncherIdentity");
    }
    fn(name);
}

void gamecore_setCABundlePath(const char *path) {
    static void (*fn)(const char *path);
    if (fn == NULL) {
        fn = coreSymbol("gamecore_setCABundlePath");
    }
    fn(path);
}

void gamecore_setTextInputModeCallback(gamecore_TextInputModeCallback cb, void *userdata) {
    static void (*fn)(gamecore_TextInputModeCallback cb, void *userdata);
    if (fn == NULL) {
        fn = coreSymbol("gamecore_setTextInputModeCallback");
    }
    fn(cb, userdata);
}

void gamecore_pushTextInput(const char *utf8) {
    static void (*fn)(const char *utf8);
    if (fn == NULL) {
        fn = coreSymbol("gamecore_pushTextInput");
    }
    fn(utf8);
}

int gamecore_isTextInputActive(void) {
    static int (*fn)(void);
    if (fn == NULL) {
        fn = coreSymbol("gamecore_isTextInputActive");
    }
    return fn();
}

double gamecore_getAverageFPS(void) {
    static double (*fn)(void);
    if (fn == NULL) {
        fn = coreSymbol("gamecore_getAverageFPS");
    }
    return fn();
}

int gamecore_getTargetFPS(void) {
    static int (*fn)(void);
    if (fn == NULL) {
        fn = coreSymbol("gamecore_getTargetFPS");
    }
    return fn();
}

const char *gamecore_getGameTitle(void) {
    static const char *(*fn)(void);
    if (fn == NULL) {
        fn = coreSymbol("gamecore_getGameTitle");
    }
    return fn();
}

void gamecore_setSafeAreaInsets(float top, float bottom, float left, float right) {
    static void (*fn)(float top, float bottom, float left, float right);
    if (fn == NULL) {
        fn = coreSymbol("gamecore_setSafeAreaInsets");
    }
    fn(top, bottom, left, right);
}

void gamecore_setHostViewportRegion(float x, float y, float w, float h, bool isPortrait) {
    static void (*fn)(float x, float y, float w, float h, bool isPortrait);
    if (fn == NULL) {
        fn = coreSymbol("gamecore_setHostViewportRegion");
    }
    fn(x, y, w, h, isPortrait);
}

void gamecore_clearHostViewportRegion(void) {
    static void (*fn)(void);
    if (fn == NULL) {
        fn = coreSymbol("gamecore_clearHostViewportRegion");
    }
    fn();
}

void *gamecore_getGameWindow(void) {
    static void *(*fn)(void);
    if (fn == NULL) {
        fn = coreSymbol("gamecore_getGameWindow");
    }
    return fn();
}

GameCoreVerticalAlignment gamecore_getVerticalAlignment(void) {
    static GameCoreVerticalAlignment (*fn)(void);
    if (fn == NULL) {
        fn = coreSymbol("gamecore_getVerticalAlignment");
    }
    return fn();
}

void gamecore_applySessionConfig(const GameCoreSessionConfig *config) {
    static void (*fn)(const GameCoreSessionConfig *config);
    if (fn == NULL) {
        fn = coreSymbol("gamecore_applySessionConfig");
    }
    fn(config);
}

void gamecore_setSetting(const char *key, const char *value) {
    static void (*fn)(const char *key, const char *value);
    if (fn == NULL) {
        fn = coreSymbol("gamecore_setSetting");
    }
    fn(key, value);
}

const char *gamecore_getDetails(void) {
    static const char *(*fn)(void);
    if (fn == NULL) {
        fn = coreSymbol("gamecore_getDetails");
    }
    return fn();
}

void gamecore_setShowViewportBounds(bool enabled) {
    static void (*fn)(bool enabled);
    if (fn == NULL) {
        fn = coreSymbol("gamecore_setShowViewportBounds");
    }
    fn(enabled);
}

void gamecore_setCheatsEnabled(bool enabled) {
    static void (*fn)(bool enabled);
    if (fn == NULL) {
        fn = coreSymbol("gamecore_setCheatsEnabled");
    }
    fn(enabled);
}

bool gamecore_getCheatsEnabled(void) {
    static bool (*fn)(void);
    if (fn == NULL) {
        fn = coreSymbol("gamecore_getCheatsEnabled");
    }
    return fn();
}

void gamecore_setGameControllerCaptureEnabled(bool enabled) {
    static void (*fn)(bool enabled);
    if (fn == NULL) {
        fn = coreSymbol("gamecore_setGameControllerCaptureEnabled");
    }
    fn(enabled);
}

void gamecore_setTouchMouseEnabled(bool enabled) {
    static void (*fn)(bool enabled);
    if (fn == NULL) {
        fn = coreSymbol("gamecore_setTouchMouseEnabled");
    }
    fn(enabled);
}

void gamecore_setViewportBoundsColor(float r, float g, float b, float a) {
    static void (*fn)(float r, float g, float b, float a);
    if (fn == NULL) {
        fn = coreSymbol("gamecore_setViewportBoundsColor");
    }
    fn(r, g, b, a);
}

void gamecore_signalErrorDismissed(void) {
    static void (*fn)(void);
    if (fn == NULL) {
        fn = coreSymbol("gamecore_signalErrorDismissed");
    }
    fn();
}

void gamecore_setErrorMessageCallback(gamecore_ErrorMessageCallback cb, void *userdata) {
    static void (*fn)(gamecore_ErrorMessageCallback cb, void *userdata);
    if (fn == NULL) {
        fn = coreSymbol("gamecore_setErrorMessageCallback");
    }
    fn(cb, userdata);
}

void gamecore_signalInfoDismissed(void) {
    static void (*fn)(void);
    if (fn == NULL) {
        fn = coreSymbol("gamecore_signalInfoDismissed");
    }
    fn();
}

void gamecore_setInfoMessageCallback(gamecore_InfoMessageCallback cb, void *userdata) {
    static void (*fn)(gamecore_InfoMessageCallback cb, void *userdata);
    if (fn == NULL) {
        fn = coreSymbol("gamecore_setInfoMessageCallback");
    }
    fn(cb, userdata);
}

void gamecore_requestPause(void) {
    static void (*fn)(void);
    if (fn == NULL) {
        fn = coreSymbol("gamecore_requestPause");
    }
    fn();
}

void gamecore_requestResume(void) {
    static void (*fn)(void);
    if (fn == NULL) {
        fn = coreSymbol("gamecore_requestResume");
    }
    fn();
}

bool gamecore_isPaused(void) {
    static bool (*fn)(void);
    if (fn == NULL) {
        fn = coreSymbol("gamecore_isPaused");
    }
    return fn();
}

bool gamecore_copySnapshotRGBA(unsigned char *dest, int destSize, int *width, int *height) {
    static bool (*fn)(unsigned char *dest, int destSize, int *width, int *height);
    if (fn == NULL) {
        fn = coreSymbol("gamecore_copySnapshotRGBA");
    }
    return fn(dest, destSize, width, height);
}

bool gamecore_getSnapshotSize(int *width, int *height) {
    static bool (*fn)(int *width, int *height);
    if (fn == NULL) {
        fn = coreSymbol("gamecore_getSnapshotSize");
    }
    return fn(width, height);
}

void gamecore_setPausedCallback(gamecore_PausedCallback cb, void *userdata) {
    static void (*fn)(gamecore_PausedCallback cb, void *userdata);
    if (fn == NULL) {
        fn = coreSymbol("gamecore_setPausedCallback");
    }
    fn(cb, userdata);
}

void gamecore_setResumedCallback(gamecore_ResumedCallback cb, void *userdata) {
    static void (*fn)(gamecore_ResumedCallback cb, void *userdata);
    if (fn == NULL) {
        fn = coreSymbol("gamecore_setResumedCallback");
    }
    fn(cb, userdata);
}

void gamecore_setFrameRenderedCallback(gamecore_FrameRenderedCallback cb, void *userdata) {
    static void (*fn)(gamecore_FrameRenderedCallback cb, void *userdata);
    if (fn == NULL) {
        fn = coreSymbol("gamecore_setFrameRenderedCallback");
    }
    fn(cb, userdata);
}

void gamecore_setFastForwardMultiplier(int multiplier) {
    static void (*fn)(int multiplier);
    if (fn == NULL) {
        fn = coreSymbol("gamecore_setFastForwardMultiplier");
    }
    fn(multiplier);
}

int gamecore_getFastForwardMultiplier(void) {
    static int (*fn)(void);
    if (fn == NULL) {
        fn = coreSymbol("gamecore_getFastForwardMultiplier");
    }
    return fn();
}

void gamecore_resetSessionState(void) {
    static void (*fn)(void);
    if (fn == NULL) {
        fn = coreSymbol("gamecore_resetSessionState");
    }
    fn();
}

void gamecore_killSession(void) {
    static void (*fn)(void);
    if (fn == NULL) {
        fn = coreSymbol("gamecore_killSession");
    }
    fn();
}

void gamecore_setDebugLogPath(const char *path) {
    static void (*fn)(const char *path);
    if (fn == NULL) {
        fn = coreSymbol("gamecore_setDebugLogPath");
    }
    fn(path);
}
