#!/bin/sh
# Generate the C file that lets the game process call its core without
# linking it. The same file serves every core, because every core
# exports each name of GameCore.h as it is.
#
# The game process opens the core with dlopen and RTLD_LOCAL, so the
# linker cannot resolve a single core name at build time. This writes
# one forwarder for every function GameCore.h declares. Each forwarder
# looks its symbol up in the open core on first use.
#
# Usage:
#   tools/gamecore/generate-core-forwarders.sh [--out <file>]
set -eu

ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
HEADER="$ROOT/cores/GameCore.h"
OUT="$ROOT/ios/Empo/GameProcess/GameCoreForwarders.c"

while [ "$#" -gt 0 ]; do
    case "$1" in
        --out)
            OUT="$2"
            shift 2
            ;;
        *)
            echo "generate-core-forwarders: unknown argument $1" >&2
            exit 2
            ;;
    esac
done

[ -f "$HEADER" ] || {
    echo "generate-core-forwarders: $HEADER missing" >&2
    exit 1
}

TMP="$(mktemp "${TMPDIR:-/tmp}/mkxp-forwarders.XXXXXX")"
trap 'rm -f "$TMP"' EXIT

cat >"$TMP" <<'HEAD'
// Generated by tools/gamecore/generate-core-forwarders.sh from
// cores/GameCore.h. Do not edit by hand.

#include "EmpoCore.h"

#include <dlfcn.h>
#include <stdio.h>
#include <stdlib.h>

#include "GameCore.h"

static void *gCore;

int EmpoCoreOpen(const char *binaryPath) {
    if (gCore != NULL) {
        fprintf(stderr, "EmpoCore: a core is open, refusing %s\n", binaryPath);
        return 0;
    }
    // RTLD_LOCAL keeps the core's names out of the global namespace.
    // Every name below reaches this image through its own handle.
    void *core = dlopen(binaryPath, RTLD_NOW | RTLD_LOCAL);
    if (core == NULL) {
        fprintf(stderr, "EmpoCore: cannot open %s: %s\n", binaryPath, dlerror());
        return 0;
    }
    gCore = core;
    return 1;
}

// dlsym with the core's handle searches that image only, so the core
// answers under the same name without a clash with the forwarder below.
static void *coreSymbol(const char *symbol) {
    void *address = gCore != NULL ? dlsym(gCore, symbol) : NULL;
    if (address == NULL) {
        // Either the process called the core before it opened one, or
        // the framework and this file were built from different
        // headers. Both are build errors, and a silent no-op would hide
        // them until a game misbehaved.
        fprintf(stderr, "EmpoCore: %s is not available (core open: %d)\n", symbol,
                gCore != NULL);
        abort();
    }
    return address;
}

HEAD

awk -f "$ROOT/tools/gamecore/forwarders.awk" "$HEADER" >>"$TMP"

COUNT="$(grep -c '^    if (fn == NULL) {' "$TMP")"
if [ "$COUNT" -lt 40 ]; then
    echo "generate-core-forwarders: only $COUNT forwarders parsed, refusing" >&2
    exit 1
fi

clang-format -i --style=file:"$ROOT/.clang-format" "$TMP"
mkdir -p "$(dirname "$OUT")"
mv "$TMP" "$OUT"
trap - EXIT
echo "generate-core-forwarders: wrote $COUNT forwarders to $OUT"
