#!/bin/sh
# Generate the C file that lets Empo call the open core without linking
# it. The same file serves MkxpCore and PsdkCore. Each core answers this
# interface under its own prefix, and the forwarder puts the open core's
# prefix in front of the name.
#
# Empo opens the core with dlopen and RTLD_LOCAL, so the linker cannot
# resolve a single core name at build time. This writes one forwarder
# for every function GameCore.h declares. Each forwarder looks its
# symbol up in the open core on first use, so every Swift and ObjC call
# site stays as it is.
#
# Usage:
#   tools/gamecore/generate-core-forwarders.sh [--out <file>]
set -eu

ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
HEADER="$ROOT/ios/Empo/src/App/GameCore.h"
OUT="$ROOT/ios/Empo/src/App/GameCoreForwarders.c"

while [ "$#" -gt 0 ]; do
    case "$1" in
        --out)
            OUT="$2"
            shift 2
            ;;
        *)
            echo "generate-core-forwarders: unknown argument $1" >&2
            exit 2
            ;;
    esac
done

[ -f "$HEADER" ] || {
    echo "generate-core-forwarders: $HEADER missing" >&2
    exit 1
}

TMP="$(mktemp "${TMPDIR:-/tmp}/mkxp-forwarders.XXXXXX")"
trap 'rm -f "$TMP"' EXIT

cat >"$TMP" <<'HEAD'
// Generated by tools/gamecore/generate-core-forwarders.sh from
// ios/Empo/src/App/GameCore.h. Do not edit by hand.

#include "EmpoCore.h"

#include <dlfcn.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "GameCore.h"

static void *gCore;
static char gSymbolPrefix[16];

int EmpoCoreOpen(const char *binaryPath, const char *symbolPrefix) {
    if (gCore != NULL) {
        return 1;
    }
    // RTLD_LOCAL keeps the core's names out of the global namespace, so
    // a second core opened later cannot bind to them. Every name below
    // reaches this image through its own handle.
    gCore = dlopen(binaryPath, RTLD_NOW | RTLD_LOCAL);
    if (gCore == NULL) {
        fprintf(stderr, "EmpoCore: cannot open %s: %s\n", binaryPath, dlerror());
        return 0;
    }
    snprintf(gSymbolPrefix, sizeof(gSymbolPrefix), "%s", symbolPrefix);
    return 1;
}

int EmpoCoreIsOpen(void) { return gCore != NULL; }

// Each core answers this interface under its own prefix: MkxpCore
// answers mkxp_setGamePath, PsdkCore answers psdk_setGamePath. The
// caller of EmpoCoreOpen says which one it opened.
static void *coreSymbol(const char *name) {
    char symbol[96];
    snprintf(symbol, sizeof(symbol), "%s%s", gSymbolPrefix, name);
    void *address = gCore != NULL ? dlsym(gCore, symbol) : NULL;
    if (address == NULL) {
        // Either the app called the core before it picked a game, or
        // the framework and this file were built from different
        // headers. Both are build errors, and a silent no-op would hide
        // them until a game misbehaved.
        fprintf(stderr, "EmpoCore: %s is not available (core open: %d)\n", symbol,
                gCore != NULL);
        abort();
    }
    return address;
}

HEAD

awk -f "$ROOT/tools/gamecore/forwarders.awk" "$HEADER" >>"$TMP"

COUNT="$(grep -c '^    if (fn == NULL) {' "$TMP")"
if [ "$COUNT" -lt 80 ]; then
    echo "generate-core-forwarders: only $COUNT forwarders parsed, refusing" >&2
    exit 1
fi

mkdir -p "$(dirname "$OUT")"
mv "$TMP" "$OUT"
trap - EXIT
echo "generate-core-forwarders: wrote $COUNT forwarders to $OUT"
