#!/bin/sh
# Generate the C file that lets Empo call the open core without linking
# it. The same file serves every core, because every core exports each
# name of GameCore.h as it is.
#
# Empo opens the core with dlopen and RTLD_LOCAL, so the linker cannot
# resolve a single core name at build time. This writes one forwarder
# for every function GameCore.h declares. Each forwarder looks its
# symbol up in the open core on first use, and again after a different
# core opens, so every Swift and ObjC call
# site stays as it is.
#
# Usage:
#   tools/gamecore/generate-core-forwarders.sh [--out <file>]
set -eu

ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
HEADER="$ROOT/cores/GameCore.h"
OUT="$ROOT/ios/Empo/src/App/GameCoreForwarders.c"

while [ "$#" -gt 0 ]; do
    case "$1" in
        --out)
            OUT="$2"
            shift 2
            ;;
        *)
            echo "generate-core-forwarders: unknown argument $1" >&2
            exit 2
            ;;
    esac
done

[ -f "$HEADER" ] || {
    echo "generate-core-forwarders: $HEADER missing" >&2
    exit 1
}

TMP="$(mktemp "${TMPDIR:-/tmp}/mkxp-forwarders.XXXXXX")"
trap 'rm -f "$TMP"' EXIT

cat >"$TMP" <<'HEAD'
// Generated by tools/gamecore/generate-core-forwarders.sh from
// cores/GameCore.h. Do not edit by hand.

#include "EmpoCore.h"

#include <dlfcn.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "GameCore.h"

static void *gCore;
static char gCorePath[1024];
// Goes up each time a different core opens. A forwarder looks its
// symbol up again when this changed.
static unsigned gCoreGeneration;
static int gSessionKilled;

int EmpoCoreOpen(const char *binaryPath) {
    if (gCore != NULL && strcmp(gCorePath, binaryPath) == 0) {
        gSessionKilled = 0;
        return 1;
    }
    if (gCore != NULL && !gSessionKilled) {
        // The open core still holds a game, and its threads, globals
        // and working directory would run next to the new engine.
        fprintf(stderr, "EmpoCore: %s holds a game, refusing %s\n", gCorePath, binaryPath);
        return 0;
    }
    // RTLD_LOCAL keeps the core's names out of the global namespace.
    // Every name below reaches this image through its own handle.
    //
    // A killed core stays loaded: dlclose does not unload an image that
    // ran static initializers or registered ObjC classes. It holds no
    // game, and scripts/audit-ipa.sh keeps its class names its own.
    void *core = dlopen(binaryPath, RTLD_NOW | RTLD_LOCAL);
    if (core == NULL) {
        fprintf(stderr, "EmpoCore: cannot open %s: %s\n", binaryPath, dlerror());
        return 0;
    }
    gCore = core;
    gCoreGeneration++;
    gSessionKilled = 0;
    snprintf(gCorePath, sizeof(gCorePath), "%s", binaryPath);
    return 1;
}

void EmpoCoreKillSession(void) {
    gamecore_killSession();
    gSessionKilled = 1;
}

int EmpoCoreIsOpen(void) { return gCore != NULL; }

// dlsym with the core's handle searches that image only, so each core
// answers under the same name without a clash with the forwarder below
// or with another core that stays loaded after a kill.
static void *coreSymbol(const char *symbol) {
    void *address = gCore != NULL ? dlsym(gCore, symbol) : NULL;
    if (address == NULL) {
        // Either the app called the core before it picked a game, or
        // the framework and this file were built from different
        // headers. Both are build errors, and a silent no-op would hide
        // them until a game misbehaved.
        fprintf(stderr, "EmpoCore: %s is not available (core open: %d)\n", symbol,
                gCore != NULL);
        abort();
    }
    return address;
}

HEAD

awk -f "$ROOT/tools/gamecore/forwarders.awk" "$HEADER" >>"$TMP"

COUNT="$(grep -c '^    if (fn == NULL || generation != gCoreGeneration) {' "$TMP")"
if [ "$COUNT" -lt 40 ]; then
    echo "generate-core-forwarders: only $COUNT forwarders parsed, refusing" >&2
    exit 1
fi

clang-format -i --style=file:"$ROOT/.clang-format" "$TMP"
mkdir -p "$(dirname "$OUT")"
mv "$TMP" "$OUT"
trap - EXIT
echo "generate-core-forwarders: wrote $COUNT forwarders to $OUT"
