// Writes docs/changelog.mdx from CHANGELOG.md and from the engine commits
// between the submodule pins of two releases. The docs scripts run it before
// Blume, and the output is git-ignored, so the site page can never drift
// from the changelog.

const source = await Bun.file("CHANGELOG.md").text();
const keptGroups = ["Features", "Bug Fixes", "Performance", "UI"];
const engineGroups: Record<string, string> = { feat: "Features", fix: "Bug Fixes", perf: "Performance" };
const engineSkippedScopes = ["build", "ci", "deps", "docs", "test"];
const releaseTag = (version: string) =>
  `https://github.com/mateo-m/empo-app/releases/tag/v${version}`;

const git = (...args: string[]) => {
  const run = Bun.spawnSync(["git", ...args]);
  return run.exitCode === 0 ? run.stdout.toString().trim() : undefined;
};

// The engine commit a release shipped. Missing when the tag is not fetched.
const enginePin = (version: string) => git("rev-parse", `v${version}:mkxp-z-apple-mobile`);

const engineEntries = (from: string, to: string) => {
  const log = git("-C", "mkxp-z-apple-mobile", "log", "--format=%s", `${from}..${to}`) ?? "";
  const entries = new Map<string, string[]>();
  for (const subject of log.split("\n")) {
    const commit = subject.match(/^(feat|fix|perf)(?:\(([^)]*)\))?!?: (.+?)(?: \(#\d+\))?$/);
    if (!commit || engineSkippedScopes.includes(commit[2] ?? "")) continue;
    const group = engineGroups[commit[1]];
    const text = commit[3].charAt(0).toUpperCase() + commit[3].slice(1);
    entries.set(group, [...(entries.get(group) ?? []), `- ${text}`]);
  }
  return entries;
};

type Release = { version: string; date: string; groups: Map<string, string[]> };

const releases: Release[] = [];
let current: Release | undefined;
let group: string | undefined;

for (const line of source.split("\n")) {
  const release = line.match(/^## (\S+) - (\d{4}-\d{2}-\d{2})$/);
  if (release) {
    current = { version: release[1], date: release[2], groups: new Map() };
    releases.push(current);
    group = undefined;
    continue;
  }
  if (line.startsWith("## ")) {
    current = undefined;
    continue;
  }
  const heading = line.match(/^### (.+)$/);
  if (heading) {
    group = heading[1];
    continue;
  }
  if (!current || !group || !line.startsWith("- ")) continue;
  if (!keptGroups.includes(group)) continue;
  const entry = line
    .replace(/ \(\[`[0-9a-f]+`\]\(https:\/\/github\.com\/[^)]+\)\)$/, "")
    .replace(/ \(#\d+\)$/, "");
  const entries = current.groups.get(group) ?? [];
  entries.push(entry);
  current.groups.set(group, entries);
}

releases.forEach((release, index) => {
  const previous = releases[index + 1];
  const to = enginePin(release.version);
  const from = previous && enginePin(previous.version);
  if (!to || !from) return;
  for (const [group, entries] of engineEntries(from, to)) {
    release.groups.set(group, [...(release.groups.get(group) ?? []), ...entries]);
  }
});

const sections = releases.map((release) => {
  const parts = [`## ${release.version}`, "", `Released ${release.date}. [Download](${releaseTag(release.version)}).`];
  if (release.groups.size === 0) {
    parts.push("", "A maintenance release with no player-facing change.");
  }
  for (const name of keptGroups) {
    const entries = release.groups.get(name);
    if (!entries) continue;
    parts.push("", `### ${name}`, "", ...entries);
  }
  return parts.join("\n");
});

const page = `---
title: What's new
description: The player-facing changes in each Empo release, derived from the changelog.
sidebar:
  icon: sparkles
---

{/* Generated by tools/changelog-page.ts from CHANGELOG.md. Do not edit. */}

Each release ships an \`.ipa\` file on the
[Releases page](https://github.com/mateo-m/empo-app/releases). This page lists the features,
the bug fixes, and the performance work in each one. The full
[CHANGELOG.md](https://github.com/mateo-m/empo-app/blob/main/CHANGELOG.md) also lists the
build and documentation work.

${sections.join("\n\n")}
`;

await Bun.write("docs/changelog.mdx", page);
console.log(`docs/changelog.mdx: ${releases.length} releases`);
