// Writes the docs pages that mirror the markdown files at the repository root.
// GitHub renders those files. The docs scripts run this before Blume, and the
// output is git-ignored, so the site pages never drift from the root files.

const pages = [
  {
    source: "PRIVACY.md",
    target: "docs/privacy.mdx",
    frontmatter: {
      title: "Privacy policy",
      description: "What Empo collects and what leaves your device.",
      icon: "shield",
    },
  },
  {
    source: "TERMS.md",
    target: "docs/terms.mdx",
    frontmatter: {
      title: "Terms of use",
      description: "The terms you accept when you use Empo, and the limits on what Empo promises.",
      icon: "scale",
    },
  },
  {
    source: "SUPPORT.md",
    target: "docs/community.mdx",
    frontmatter: {
      title: "Community and support",
      description:
        "Where to ask for help, how to report a game that does not work, and how to collect the logs a report needs.",
      icon: "message-circle",
    },
  },
];

for (const page of pages) {
  const body = await Bun.file(page.source).text();
  // MDX reads "{" and "<" as code, so a plain markdown file must not use them.
  const unsafe = body.match(/[{<]/);
  if (unsafe) {
    throw new Error(`${page.source} contains "${unsafe[0]}", which MDX does not read as text.`);
  }
  const output = `---
title: ${page.frontmatter.title}
description: ${page.frontmatter.description}
sidebar:
  icon: ${page.frontmatter.icon}
---

{/* Generated by tools/root-pages.ts from ${page.source}. Do not edit. */}

${body}`;
  await Bun.write(page.target, output);
  console.log(`${page.target}: from ${page.source}`);
}
